### ISSUE TITLE
No pagination (Next Page button) in "Vote Details" 

### ISSUE THREAD

**Issue by loriIoTeX** [iotexproject/iotex-explorer#1]
No pagination (Next Page button) in "Vote Details". It only shows at most 9 Tx hash. Cannot check the rest of the votes.

**Comment by loriIoTeX** [comment]
https://iotexscan.io/address/io1qyqsyqcyzl6j8zlyr79r09sv73fprv6ja4qjeltysa8mlk

**Comment by Fabryprog** [comment]
I see frontend code and pagination is enabled. It can be a backend error....

The bug was reproduced here: https://iotexscan.io/address/io1qyqsqqqqqtlq2hd485v402nd75tu2n0zpltcgjrk420397

There are more than 10 votes (sended my address) but backend return ever 9 rows!!!

**Comment by xiaxiangzhou** [comment]
@Fabryprog  seems the link you paste here did not reproduce the problem

**Comment by xiaxiangzhou** [comment]
Those link did not reproduce, let's wait for another bug report
