### ISSUE TITLE
Address age display issue

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-explorer#1008]
Age: 4 months ago `(date string)`
![image](https://user-images.githubusercontent.com/6645185/64834584-af450b00-d60c-11e9-93eb-214fcb3a7796.png)

**Comment by gyanpgupta** [comment]
@nmhung1210, Assuming age should be displayed like ?
Age: Tue Sep 10 2019

**Comment by gyanpgupta** [comment]
@nmhung1210 @puncsky  can we close this issue its already fixed in previous pull requests.
