### ISSUE TITLE
bug: vita amount does not update in /address/x when search from a new address

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1018]
repo steps:

1. go to https://www.iotexscan.io/address/io13zt8sznez2pf0q0hqdz2hyl938wak2fsjgdeml
2. put io17cmrextyfeu4gddwd89g5qncedsnc553dhz7xa in address and enter
3. vita shows non zero value
4. refresh page. it becomes zero.

**Comment by nmhung1210** [comment]
Closed in favor of #1028
