### ISSUE TITLE
error handling of all graphql queries

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#108]

**Comment by uu-z** [comment]
@nmhung1210 you can refer https://www.apollographql.com/docs/react/features/error-handling

**Comment by nmhung1210** [comment]
> @nmhung1210 you can refer https://www.apollographql.com/docs/react/features/error-handling

Thanks :). Btw, do we have any design for the error message box? Do we have any policy or rules to retry?

**Comment by uu-z** [comment]
> > @nmhung1210 you can refer https://www.apollographql.com/docs/react/features/error-handling
> 
> Thanks :). Btw, do we have any design for the error message box? Do we have any policy or rules to retry?

just using antd notification show the error message.

**Comment by nmhung1210** [comment]
> > > @nmhung1210 you can refer https://www.apollographql.com/docs/react/features/error-handling
> > 
> > 
> > Thanks :). Btw, do we have any design for the error message box? Do we have any policy or rules to retry?
> 
> just using antd notification show the error message.

ok, got it! Thanks :)
