### ISSUE TITLE
Support solc 0.5.0+

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#1081]
We may need to provide both 0.4.24 and 0.5.0 compilation options

**Comment by gyanpgupta** [comment]
![Screenshot from 2019-10-22 19-34-48](https://user-images.githubusercontent.com/36037560/67294155-18b91300-f503-11e9-8603-c2b890e792c7.png)

@puncsky , I think this is the place we are talking about and I am getting this error on console. while using v^0.5.0 its working fine with v^0.4.24. I found this error related issue here https://github.com/ethereum/solc-js/issues/321. if you have any idea please help.

**Comment by gyanpgupta** [comment]
@puncsky  @nmhung1210  0.5.0 has some breaking changes like following:
C API (libsolc / raw soljson.js): Removed the version, license, compileSingle, compileJSON, compileJSONCallback methods and replaced them with the solidity_license, solidity_version and solidity_compile methods.
https://github.com/ethereum/solidity/blob/v0.5.0/Changelog.md
any suggestion?
