### ISSUE TITLE
Contract page doesn't list anything

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#1085]
Contract page doesn't list anything, but it should

<img width="1255" alt="Screen Shot 2019-10-17 at 2 51 37 PM" src="https://user-images.githubusercontent.com/35021395/67050607-bb315a80-f0ed-11e9-818f-445fddb467d0.png">

For example, https://www.iotexscan.io/address/io1xpq62aw85uqzrccg9y5hnryv8ld2nkpycc3gza

It at least should has this action: https://www.iotexscan.io/action/0fed7f77e4898801f2b6663ffbdd6e0616f0f403f6c9ff7c3c0974373874ad1f

**Comment by nmhung1210** [comment]
Ref. https://github.com/iotexproject/iotex-analytics/issues/112
