### ISSUE TITLE
Feedback for Native Staking Frontend

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#1095]
1. ```IOTX-E (ERC-20)``` and ```IOTX```
![Screen Shot 2019-10-21 at 6 30 38 PM](https://user-images.githubusercontent.com/989846/67254240-e63ee580-f430-11e9-9db1-25d8d745b64a.png)
Similar here https://member-testnet.iotex.io/my-votes

2. native staking can be 1050 epoch at most.
![Screen Shot 2019-10-21 at 6 36 40 PM](https://user-images.githubusercontent.com/989846/67254424-bf34e380-f431-11e9-8428-34a37f09c372.png)

3. I used an old iopay desktop which didn't work but the latest 0.6.2 works. Pls specify the version (>=0.6.2) here
![Screen Shot 2019-10-21 at 6 38 04 PM](https://user-images.githubusercontent.com/989846/67254456-f5726300-f431-11e9-96de-afb6f46fefb7.png)

4. I voted for "coingecko" but it says "coi" in https://member-testnet.iotex.io/my-votes
![Screen Shot 2019-10-21 at 6 42 53 PM](https://user-images.githubusercontent.com/989846/67254582-a7aa2a80-f432-11e9-9020-f9f8242ec399.png)

5. "Add votes" doesn't work -- tried twice, my txs were thrown away by the network -- what is going on? https://www.iotexscan.io/action/781e8fe143f71261817705ab8024298c5617a7ffbb073e9b4791174319ae40c5

6. "Restake" to turn on/off auto-staking and iopay has no response.

7. https://member-testnet.iotex.io/my-votes on IOTX (native) tab, we should show the native addr and info, not IOTX-E addr and info.
<img width="1227" alt="Screen Shot 2019-10-21 at 10 33 01 PM" src="https://user-images.githubusercontent.com/989846/67260924-eea81800-f452-11e9-9a08-270084304465.png">

**Comment by sxlwar** [comment]
fixed in
 https://github.com/iotexproject/web-bp/pull/1387/commits/15c2d9c23248f7b7d568cdafc9e4e278ff84d4f3 
https://github.com/iotexproject/web-bp/pull/1387/commits/bc784e520bef7cb470f73d9d285b955adce3243e
https://github.com/iotexproject/web-bp/pull/1387/commits/dc1369981fa71a5359f1eb898701ef616707fdb1
