### ISSUE TITLE
0.6.2 has no vita section on my laptop

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#1105]
<img width="312" alt="Screen Shot 2019-10-22 at 4 36 38 PM" src="https://user-images.githubusercontent.com/989846/67343455-2c0bb480-f4ea-11e9-935f-77244fdded6f.png">
<img width="1196" alt="Screen Shot 2019-10-22 at 4 36 23 PM" src="https://user-images.githubusercontent.com/989846/67343456-2ca44b00-f4ea-11e9-88b1-4684c93f3cf6.png">

**Comment by puncsky** [comment]
please remove your local config at `/Users/{yourUserName}/Library/Application Support/Electron/iotex-wallet-conf.json`

**Comment by raullenchai** [comment]
```
/Users/raullen/Library/Application Support
➜  Application Support cd Ethereum\ Wallet/
Ethereum\ Wallet/  eos-studio/        eosio/
```

I don't have such a file

**Comment by raullenchai** [comment]
same problem in 0.6.3

<img width="1155" alt="Screen Shot 2019-11-01 at 9 17 50 AM" src="https://user-images.githubusercontent.com/989846/68039053-880fcf00-fc88-11e9-9d09-f15303e4554a.png">

**Comment by puncsky** [comment]
remove `/Users/{yourUserName}/Library/Application\ Support/ioPay/iotex-wallet-conf.json`

**Comment by raullenchai** [comment]
Cool, thx.
