### ISSUE TITLE
Lost of Data on XRC20 Transactions history

### ISSUE THREAD

**Issue by JoeGo007** [iotexproject/iotex-explorer#1111]
Old data about XRC20 Transactions on iotexscan.io seems to have been lost. For instance https://iotexscan.io/address/io17dlnnt4greelt2cw7g9wnsqkpyhv9ehv2pmd5d

**Comment by lizhefeng** [comment]
This is expected. We need to rebuild the XRC20 table in analytics for the old data.

**Comment by puncsky** [comment]
@lizhefeng any actionable item for this issue?

**Comment by JoeGo007** [comment]
Solved
