### ISSUE TITLE
Testnet hash link directed to Mainnet Explorer

### ISSUE THREAD

**Issue by loriIoTeX** [iotexproject/iotex-explorer#1115]
![image](https://user-images.githubusercontent.com/38968374/67990168-4a606700-fbf2-11e9-877a-c718fc4b9af0.png)

https://iotexscan.io/action/f6db7d4f9d1dd128133ff8a306384814d7945c60176da0fc8b9e5aa872057978

**Comment by puncsky** [comment]
moved to https://github.com/iotexproject/web-bp/issues/1402
