### ISSUE TITLE
policy redirects to 404

### ISSUE THREAD

**Issue by gyanpgupta** [iotexproject/iotex-explorer#1116]
![FooterTypo](https://user-images.githubusercontent.com/36037560/68017782-7e548e80-fcbd-11e9-8e93-e356966379a5.png)

there's typo issue too it should be **Term of use** instead **Team of use**

**Comment by puncsky** [comment]
https://v1.iotex.io/policy

**Comment by gyanpgupta** [comment]
> https://v1.iotex.io/policy
we are using footer from iotex-react-footer so i think we should change the URL there.
