### ISSUE TITLE
handle error properly

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1127]
<img width="507" alt="Screen Shot 2019-11-05 at 6 09 50 PM" src="https://user-images.githubusercontent.com/1387285/68262284-a7478d00-fff7-11e9-88d7-5cfc3aafe0d8.png">

we have displayed not found so we'd better not display 3 INVALID_ARGUMENT ...

**Comment by gyanpgupta** [comment]
@puncsky  could not reproduce this issue, I think its fixed already.
