### ISSUE TITLE
update footer 

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1134]
to make it look like

![Screen Shot 2019-11-07 at 5 50 59 PM](https://user-images.githubusercontent.com/1387285/68443479-cfb2c100-0188-11ea-8e61-14a322875e23.png)

in www.iotex.io

**Comment by raullenchai** [comment]
<img width="1393" alt="Screen Shot 2020-07-21 at 9 33 16 AM" src="https://user-images.githubusercontent.com/989846/88081429-36b8b000-cb35-11ea-9c35-aff6495159ed.png">

**Comment by raullenchai** [comment]
So this is done
