### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by eLLora2** [iotexproject/iotex-explorer#1146]
Would it be better if its left aligned
![Screen Shot 2019-11-08 at 3 27 16 PM](https://user-images.githubusercontent.com/57690923/68723220-d5cfe580-056c-11ea-9e6b-34c15d7e533a.png)

**Comment by raullenchai** [comment]
@puncsky how do u think

**Comment by gyanpgupta** [comment]
@raullenchai Already done!
