### ISSUE TITLE
ios iopay crash 

### ISSUE THREAD

**Issue by FishMeat** [iotexproject/iotex-explorer#1155]
![IMG_2189](https://user-images.githubusercontent.com/7263252/69037538-0b6c4700-0a23-11ea-82a3-4c0d095b86e2.PNG)

click  TrustDice icon, it will crash 

phone: iPhone 11

**Comment by guoxiaopang** [comment]
Thanks for feedback。This bug has been fixed in the next version and is expected to be released through review in the past few days.
