### ISSUE TITLE
[master] v2

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1178]
* 2019-12-17 18:08 @nmhung1210 [master][XRC20] support multiple XRC20 tokens https://github.com/iotexproject/iotex-explorer/issues/1209
  * ~[XRC20] remove webBpApolloClient and use `address-meta.json` file for the mapping https://github.com/iotexproject/iotex-explorer/issues/1206~
  * ~add readme on how to add meta for an address https://github.com/iotexproject/iotex-explorer/issues/1208~
  * ~[XRC20] Token Tracker https://github.com/iotexproject/iotex-explorer/issues/1207~
* ~token holders ranking and percentage~
* analytics (DAU, MAU, Stickiness = (DAU/MAU)*100), Uptime)
* Contract IDE v2

**Comment by nmhung1210** [comment]
@puncsky regarding Contract IDE v2 will use start with Remix IDE source or something else?
