### ISSUE TITLE
Unreadable menu texts

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-explorer#1215]
![image](https://user-images.githubusercontent.com/6645185/71239465-3656fd00-2339-11ea-91ba-0dde8f047cf0.png)

**Comment by oyosc** [comment]
please show me the branch and the current commit id in frontend server, because in localhost, the newest of master branch not find this problem

**Comment by nmhung1210** [comment]
Pls check https://iotexscan.io/
