### ISSUE TITLE
English string too long in right-side boxes

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1221]
The text "_XX minutes from now_" in the "recent blocks"boxes on the right side is too long for non-HD monitors (see picture below on a ~1300x760 pixel screen).

Possibly "_XX minutes ago_" would fit most  screens.

Also the string "from now" appears untranslated in other languages as the lokalise app does not show it among translable items.

![image](https://user-images.githubusercontent.com/11096047/71667475-87b5b200-2d65-11ea-88e6-c8f810eb3d73.png)

**Comment by puncsky** [comment]
@puncsky
