### ISSUE TITLE
[master] XRC721 token display on all devices

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1229]
1. https://github.com/iotexproject/iotex-analytics/issues/156
2. 
    * iotex-explorer
    * iopay-ios
    * iopay-android

**Comment by nmhung1210** [comment]
ref. https://github.com/iotexproject/iotex-analytics/issues/200

**Comment by puncsky** [comment]
since the api is done, the next step is to display it literally. I don't think we need design in this phase.
