### ISSUE TITLE
why is claiming vita's sender is 000..?

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1238]
![21580252850_ pic_hd](https://user-images.githubusercontent.com/1387285/73314365-86e83280-41e2-11ea-99fd-626b12e06285.jpg)

**Comment by nmhung1210** [comment]
![image](https://user-images.githubusercontent.com/6645185/78065924-3e095180-73be-11ea-95b9-761ebb1b33be.png)

Those data came from analytics.
