### ISSUE TITLE
Show reward pool balance

### ISSUE THREAD

**Issue by lizhefeng** [iotexproject/iotex-explorer#1239]
https://github.com/iotexproject/iotex-core/issues/1853

**Comment by nmhung1210** [comment]
@lizhefeng could you please advise on which API can be used to get the reward pool balance?
@puncsky could you please advise on the design of this? where should we display the reward pool balance information?

**Comment by puncsky** [comment]
Just checked the original ticket iotexproject/iotex-core#1853. I don't know that "reward pool balance" is.

**Comment by puncsky** [comment]
as a native token stats, let's add it to the homepage.

**Comment by nmhung1210** [comment]
> as a native token stats, let's add it to the homepage.

Might I have more detail of how to read that reward pool balance?

**Comment by puncsky** [comment]
![explorer-stats](https://user-images.githubusercontent.com/1387285/79179844-5f563e80-7dbd-11ea-9b45-0c678dc318aa.png)

**Comment by puncsky** [comment]
> > as a native token stats, let's add it to the homepage.
> 
> Might I have more detail of how to read that reward pool balance?

please sync with @lizhefeng

**Comment by nmhung1210** [comment]
@lizhefeng could you please help to provide details of how can we read the reward pool balance from iotex-explorer site? Is there any API available for this information?

**Comment by puncsky** [comment]
I just pinged @lizhefeng and let's wait for his response

**Comment by lizhefeng** [comment]
@nmhung1210 
Please refer to the following iotex-core api example to read available reward:

```
// AvailableBalance == Rewards in the pool that has not been issued to anyone
	request := &iotexapi.ReadStateRequest{
		ProtocolID: []byte("rewarding"),
		MethodName: []byte("AvailableBalance"),
	}
	response, err := cli.ReadState(ctx, request)
	if err != nil {
		sta, ok := status.FromError(err)
		if ok {
			return output.NewError(output.APIError, sta.Message(), nil)
		}
		return output.NewError(output.NetworkError, "failed to invoke ReadState api", err)
	}
	availableRewardRau, ok := big.NewInt(0).SetString(string(response.Data), 10)
	if !ok {
		return output.NewError(output.ConvertError, "failed to convert string into big int", err)
	}
```

**Comment by nmhung1210** [comment]
> @nmhung1210
> Please refer to the following iotex-core api example to read available reward:
> 
> ```
> // AvailableBalance == Rewards in the pool that has not been issued to anyone
> 	request := &iotexapi.ReadStateRequest{
> 		ProtocolID: []byte("rewarding"),
> 		MethodName: []byte("AvailableBalance"),
> 	}
> 	response, err := cli.ReadState(ctx, request)
> 	if err != nil {
> 		sta, ok := status.FromError(err)
> 		if ok {
> 			return output.NewError(output.APIError, sta.Message(), nil)
> 		}
> 		return output.NewError(output.NetworkError, "failed to invoke ReadState api", err)
> 	}
> 	availableRewardRau, ok := big.NewInt(0).SetString(string(response.Data), 10)
> 	if !ok {
> 		return output.NewError(output.ConvertError, "failed to convert string into big int", err)
> 	}
> ```

Thank you @lizhefeng ! Honestly, I don't know what to do with this. @puncsky could you please advice?

**Comment by puncsky** [comment]
call antenna rpc method `readState(req: IReadStateRequest): Promise<IReadStateResponse>;`

**Comment by guo** [comment]
not needed
