### ISSUE TITLE
empty contents with long paginations

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1246]
![Screen Shot 2020-02-11 at 8 19 53 PM](https://user-images.githubusercontent.com/1387285/74302617-f6464200-4d0b-11ea-9116-2b179faf11a6.png)

go to https://www.iotexscan.io/address/io1zn9mn4v63jg3047ylqx9nqaqz0ev659777q3xc#xrc_transactions

click xrc20 transactions

and an empty transaction table should have no pagination

**Comment by nmhung1210** [comment]
dependency: https://github.com/iotexproject/iotex-analytics/issues/170

**Comment by nmhung1210** [comment]
Closed in favor of  #1266
