### ISSUE TITLE
desktop wallet native staking fail

### ISSUE THREAD

**Issue by anshuomomo** [iotexproject/iotex-explorer#1249]
e64db9a0c44ce960bc8302a1deceaa7a907ca3d5ae3fd6068592b1abda89432e

**Comment by BartolomeoAndrade** [comment]
55aa30e213c611fbe0a2ee0858b8df90ef4f5c0ca2826ca7fe8fd51a3d639eda

**Comment by puncsky** [comment]
this is usually caused by improper contract params
