### ISSUE TITLE
text alignment 

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1252]
https://iotexscan.io/action/5afe94b698a6d5ae3756ca7241b3f804798782f105ca60ebb61ad87083b65faf

![Screen Shot 2020-02-18 at 4 04 47 PM](https://user-images.githubusercontent.com/1387285/74789050-69017100-5268-11ea-8ed3-e2db00418141.png)

**Comment by ety001** [comment]
I cannot reproduce this  issue.

![image](https://user-images.githubusercontent.com/801928/74792971-e45f3300-52f9-11ea-9c1d-3b3eac8d6fda.png)

Any more information?
