### ISSUE TITLE
optimize analytics loading speed

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1254]
investigate and propose potential fixes

**Comment by puncsky** [comment]
![Screen Shot 2020-02-18 at 4 42 26 PM](https://user-images.githubusercontent.com/1387285/74790857-be8c4c80-526d-11ea-9d3d-ad738caf37f8.png)

**Comment by ety001** [comment]
@puncsky 

The api's TTFB is too long.

![image](https://user-images.githubusercontent.com/801928/75013387-27b6ce80-54bf-11ea-8522-f65620958a8c.png)
