### ISSUE TITLE
Add a box for "X% IOTX Staked" 

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#1274]
<img width="966" alt="Screen Shot 2020-04-02 at 7 55 49 PM" src="https://user-images.githubusercontent.com/989846/78319409-f8629b00-751b-11ea-93b6-03bf5d46543b.png">

@puncsky pls help to route.

**Comment by loriIoTeX** [comment]
![image](https://user-images.githubusercontent.com/38968374/78617646-d4110200-782c-11ea-8260-9ce7acaee27b.png)

**Comment by puncsky** [comment]
![explorer-stats](https://user-images.githubusercontent.com/1387285/79179892-8280ee00-7dbd-11ea-8ca7-28179ad452d2.png)

**Comment by nmhung1210** [comment]
@puncsky could you please guide on how to read that % IOTX staked?

**Comment by puncsky** [comment]
> @puncsky could you please guide on how to read that % IOTX staked?

Please check web-bp and search there.
