### ISSUE TITLE
nmh plan week 2020-04-06

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1277]
last week:

* https://github.com/iotexproject/iotex-explorer/issues/1207 
* https://github.com/iotexproject/iotex-explorer/issues/1221 
* https://github.com/iotexproject/iotex-explorer/issues/1235 
* https://github.com/iotexproject/iotex-explorer/issues/1239

as I can see, 1/4 completed... 

can you plan more accurately this week?

**Comment by nmhung1210** [comment]
#1207 closed
#1221 closed
#1235 still waiting for analytics issue
#1239 Still waiting for details of API, design.
