### ISSUE TITLE
nmh's work for week 2020-04-20

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#1290]
* [x] refresh stats area  https://github.com/iotexproject/iotex-explorer/issues/1274
* [ ]  https://github.com/iotexproject/iotex-explorer/issues/1239
* [x] https://github.com/iotexproject/iotex-explorer/issues/1291
* [x]  https://github.com/iotexproject/iotex-explorer/issues/878
* [x] https://github.com/iotexproject/iotex-explorer/issues/1292

**Comment by nmhung1210** [comment]
#1239 Still waiting for the answer to where can I read that reward pool balance?

**Comment by puncsky** [comment]
closed for https://github.com/iotexproject/iotex-explorer/issues/1297
