### ISSUE TITLE
Unable to complete wallet creation on low res smartphones

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1301]
There is no "Next" button visible when installing IoPay on a Samsung J5 smartphone. It seems like a "Next" button is supposed to be showed somewhere while assigning a name to the very first wallet, but none is visible:

![photo_2020-04-30_17-47-54](https://user-images.githubusercontent.com/11096047/80731190-db18f080-8b0a-11ea-9df5-340560a7bb71.jpg)

This the screen on a Samsung J5 - Italian language.

**Comment by raullenchai** [comment]
Let's track this in iopay-android repo
