### ISSUE TITLE
Trim tailing or prefix space of address in wallet for sending

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1307]
![image](https://user-images.githubusercontent.com/448293/82285296-ff206280-994f-11ea-8757-ad7891a8c6cd.png)

**Comment by guo** [comment]
repo:
enter an address "ioxxxx" and add a space in the end.

try to send.

**Comment by raullenchai** [comment]
Pls verify if this is still an issue; if so, pls fix.
