### ISSUE TITLE
Mnemonic Phrase input should not allow browser to remember phrases

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1308]
![image](https://user-images.githubusercontent.com/448293/82308694-fe4ef700-9976-11ea-9a7e-01a5afc540f8.png)

**Comment by raullenchai** [comment]
On https://www.iotexscan.io/wallet/transfer, when ppl input Mnemonic Phrase once, it is remembered by the browser and auto-shows for next login, which should not be the case.
