### ISSUE TITLE
Mnemonic Phrase align with ledger's 24 phrase?

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1309]
it is better "Mnemonic Phrase" is aligned with ledger's 24 phrase, instead of 12 phrases.

**Comment by raullenchai** [comment]
Some useful info from https://bitcoin.stackexchange.com/questions/71878/whats-the-difference-between-12-word-seed-and-24-word-seed

```
12 words utilizes 128 (4x32) bits of entropy

18 words utilizes 192 (4x48) bits of entropy

24 words utilized 256 (4x64) bits of entropy
```

In all, 24-word is much secure but 12-word is enough for now. So if this task involves migrating 12-word users to 24-word users, I'd think it is a low pri.
