### ISSUE TITLE
[wallet]: unlock by keystore file not working

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-explorer#1316]
unlock your wallet --> by keystore --> Browse file 
file is grayed, cannot be selected

<img width="964" alt="Screen Shot 2020-05-21 at 12 46 30 PM" src="https://user-images.githubusercontent.com/12551272/82600233-73caeb00-9b62-11ea-9407-989b531a30e5.png">

**Comment by dustinxie** [comment]
so i tested, it is b/c wallet requires the filename with extension .json

can we remove this restriction and treat the input as a JSON file? if that fails then let it fail anyway
b/c the keystore file i used is copied from ioctl generated key

**Comment by puncsky** [comment]
keystore file is in `.json` extension
