### ISSUE TITLE
VITA Claim Available Badge never disappearing

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1326]
IoPay version 0.9.1, the VITA Claim Available badge does not disappear after claiming, unless IoPay app is restarted. The claim button stays enabled as well, allowing multiple claim transactions, that of course get reverted.

![image](https://user-images.githubusercontent.com/11096047/82846381-e16f7200-9ee8-11ea-9567-64081bc1078d.png)

**Comment by guo** [comment]
@hunglmtb please take a look?
