### ISSUE TITLE
balance formatting: 4 digits precision

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#133]
`#.####`

for example: here.

![image](https://user-images.githubusercontent.com/448293/54949945-6930a980-4efd-11e9-8179-d37647b81c30.png)

**Comment by puncsky** [comment]
@uu-z

**Comment by puncsky** [comment]
https://iotexscan.io/address/io1l3wc0smczyay8xq747e2hw63mzg3ctp6uf8wsg
