### ISSUE TITLE
add "Transfer ownership" to My votes --> Action

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-explorer#1330]
nsV2 has a new feature transfer ownership of your bucket, should add it to My votes --> Action

<img width="971" alt="Screen Shot 2020-05-26 at 8 20 37 PM" src="https://user-images.githubusercontent.com/12551272/82974543-12a27d80-9f8f-11ea-8d45-71a81b28bb03.png">

**Comment by guo** [comment]
dup. closing. tracking in another repo
