### ISSUE TITLE
iopay android nsv2 ui issue 

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-explorer#1331]
![381590604963_ pic_hd](https://user-images.githubusercontent.com/915849/83059806-56d56280-a00f-11ea-9c06-1e0da020e7ef.jpg)

1. words in green box is not accurate. There is no smart contract interaction anymore with nsv2
2. Long delegate name cannot show completely  or expand on mobile. etc `robotbp00...`
3. There is a weird line on the auto-stake column

**Comment by puncsky** [comment]
<img width="205" alt="Screen Shot 2020-06-04 at 5 15 30 PM" src="https://user-images.githubusercontent.com/1387285/83822823-03a28600-a687-11ea-8a42-22efff23ebe4.png">

need some spacing
