### ISSUE TITLE
Show UTF-8 encoding option for payload fields 

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1334]
![image](https://user-images.githubusercontent.com/448293/83341783-78974980-a29c-11ea-8111-36c7dd6f3a44.png)
The one used in etherscan:
![image](https://user-images.githubusercontent.com/448293/83341834-d0ce4b80-a29c-11ea-8e38-d5445c20954a.png)

**Comment by puncsky** [comment]
please use `Buffer` to address this issue

**Comment by liaojikunwork** [comment]
Should I place such a dropdown on action detail page?

**Comment by liaojikunwork** [comment]
Is it the same as https://github.com/iotexproject/iotex-explorer/issues/366 ?

**Comment by raullenchai** [comment]
> Is it the same as #366 ?

Almost, but this one has a good point - we shall give user an option to view as hex or utf8

**Comment by liaojikunwork** [comment]
So should I create that dropdown on a new row or on the payload field together?

**Comment by raullenchai** [comment]
yep, near "Payload" field
