### ISSUE TITLE
sha512 on ioPay-0.10.0.AppImage incorrect?

### ISSUE THREAD

**Issue by jmafc** [iotexproject/iotex-explorer#1353]
I downloaded `ioPay-0.10.0.AppImage` as well as the `latest-linux.yml` and then ran `sha512sum` on the former.  The resulting sum has 128 chars and looks like `c21f0a08...2e57deee` which does not agree with the `sha512`'s shown in the .yml file. Are they supposed to or is the one in the .yml for some other purpose?

**Comment by raullenchai** [comment]
Thanks for reporting, team is looking into this one.

**Comment by guo** [comment]
You can use `shasum -a 512 ioPay-0.10.0.AppImage | xxd -r -p | base64` to see the base64 encoded checksum.

**Comment by jmafc** [comment]
Ok, that worked (after installing `xxd`). However, if I may ask, why the non-obvious process? why not store the output of `shasum` which is only about 40 chars longer?

**Comment by puncsky** [comment]
checksum is generated automatically during the electron build process and it is unnecessary to customize this.
