### ISSUE TITLE
[ioPay Dekstop] hide balance

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1363]
![image](https://user-images.githubusercontent.com/448293/85941773-c625c700-b8d9-11ea-943f-8d9f01932191.png)
![image](https://user-images.githubusercontent.com/448293/85941774-c8882100-b8d9-11ea-9a00-2b57654e134c.png)

please add this feature to both web based wallet and desktop wallet.

**Comment by DengMMM** [comment]
Zeplin:
https://app.zeplin.io/project/5c81bede826def625074c12c/dashboard?seid=5ef84dfa707c097fa63d4cef
