### ISSUE TITLE
[ioPay Dekstop] show version on the top right corder

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1364]
![image](https://user-images.githubusercontent.com/448293/85941789-ece3fd80-b8d9-11ea-97a2-158e3623ff37.png)

**Comment by DengMMM** [comment]
Zeplin:
https://app.zeplin.io/project/5c81bede826def625074c12c/dashboard?seid=5ef84dfa707c097fa63d4cef
