### ISSUE TITLE
show claim reward amount

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-explorer#1365]
couple of hermes users are asking, it is very useful information to display the amount of reward claimed

<img width="950" alt="Screen Shot 2020-06-29 at 12 54 38 PM" src="https://user-images.githubusercontent.com/12551272/86049868-c328f480-ba07-11ea-8856-c88e6f1a2be7.png">

**Comment by liaojikunwork** [comment]
Is it action list page?

**Comment by raullenchai** [comment]
> Is it action list page?

I think so, looks like https://www.iotexscan.io/action?actionType=claimFromRewardingFund already has the amount

**Comment by liaojikunwork** [comment]
Should I add claimReword column and show the amount if the action type is claimFromRewardingFund?
```
claimFromRewardingFund{
          amount
          data
        }
```

**Comment by raullenchai** [comment]
No, you don't have to add new col. If type == claimFromRewardingFund, put amount from graphql query under col amount
