### ISSUE TITLE
filter action type causing the whole list empty

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1366]
![image](https://user-images.githubusercontent.com/448293/86073607-f3d55200-ba38-11ea-842e-0682f0b1a58c.png)
![image](https://user-images.githubusercontent.com/448293/86073622-fc2d8d00-ba38-11ea-904f-1d3b44c77fec.png)
![image](https://user-images.githubusercontent.com/448293/86073639-0780b880-ba39-11ea-8271-17548b592f21.png)

It should only filter the current view.

**Comment by guo** [comment]
Also, it does not need to list all actions in the list. only the list inside the current view is enough.

**Comment by raullenchai** [comment]
`plum*` types are all deprecated

**Comment by liaojikunwork** [comment]
It's already implemented.
Currently, if I click one from the filter, it navigates to actions page.
"Also, it does not need to list all actions in the list. only the list inside the current view is enough."
Does it mean I should show the filtered actions on the address page(current page)?

**Comment by raullenchai** [comment]
> It's already implemented.
> Currently, if I click one from the filter, it navigates to actions page.
> "Also, it does not need to list all actions in the list. only the list inside the current view is enough."
> Does it mean I should show the filtered actions on the address page(current page)?

@guo has the answer

**Comment by raullenchai** [comment]
<img width="1050" alt="Screen Shot 2020-07-18 at 5 53 25 PM" src="https://user-images.githubusercontent.com/989846/87864654-b5d49b00-c91f-11ea-93ec-c78aa22df209.png">

https://www.iotexscan.io/action?actionType=transfer

The “sender” and “to” fields are not properly displayed. Should be the same as https://www.iotexscan.io/action

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-07-19 at 6 50 30 AM](https://user-images.githubusercontent.com/34900782/87873061-274a3300-c98c-11ea-9d1f-845a647c4251.png)

This issue was fixed before, I think.
I checked the code related to that and tested.

When addressMeta doesn't exist, it shows the raw address.

Pls check

**Comment by raullenchai** [comment]
> <img alt="Screen Shot 2020-07-18 at 5 53 25 PM" width="1050" src="https://user-images.githubusercontent.com/989846/87864654-b5d49b00-c91f-11ea-93ec-c78aa22df209.png">
> 
> https://www.iotexscan.io/action?actionType=transfer
> 
> The “sender” and “to” fields are not properly displayed. Should be the same as https://www.iotexscan.io/action


@liaojikunwork can u fix this before we close this issue?

**Comment by liaojikunwork** [comment]
Currently, it shows the raw address if addressMeta doesn't exist.
What should I show if addressMeta doesn't exist?

**Comment by raullenchai** [comment]
<img width="1106" alt="Screen Shot 2020-07-19 at 5 00 00 PM" src="https://user-images.githubusercontent.com/989846/87888355-59d24b00-c9e1-11ea-879f-1a0ee8884c41.png">

first 18 chars + '....'

**Comment by liaojikunwork** [comment]
Exactly 18 chars + '...' or make it similar to other fields(hash)?

**Comment by raullenchai** [comment]
other fields are (18 chars + '...' ), no?

**Comment by liaojikunwork** [comment]
No, just styling

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-07-19 at 8 13 59 PM](https://user-images.githubusercontent.com/34900782/87888716-6fa13980-c9fc-11ea-8a5f-872334b63164.png)
