### ISSUE TITLE
Testnet shows errors

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#1379]
https://testnet.iotexscan.io/

![Screen Shot 2020-07-13 at 3 39 05 PM](https://user-images.githubusercontent.com/989846/87360447-fd71b600-c51e-11ea-9e2b-4b53bda0a167.png)

**Comment by puncsky** [comment]
waiting for the analytics backend deployment

**Comment by guo** [comment]
This should have been fixed.

**Comment by guo** [comment]
still have issue with cross site policy.
![image](https://user-images.githubusercontent.com/448293/87581206-6a0ac300-c68d-11ea-8a86-8b62da228001.png)
<img width="444" alt="Screen Shot 2020-07-15 at 11 21 29 AM" src="https://user-images.githubusercontent.com/448293/87581232-71ca6780-c68d-11ea-8e56-a057f77a0714.png">

**Comment by puncsky** [comment]
fixed in b92271870e68a8e75dc2dac557c4464d2d2b8c33 b92271870e68a8e75dc2dac557c4464d2d2b8c33
