### ISSUE TITLE
text misalign

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1388]
![image](https://user-images.githubusercontent.com/448293/87900526-771b0f80-ca09-11ea-9421-df5219a2f8fa.png)

May just use "Delegates" as the section header.

**Comment by liaojikunwork** [comment]
What about other languages?

```
home.stats.candidates: IoTeX-Konsensdelegierte
home.stats.candidates: 'Consensus Delegates / Delegates'
home.stats.candidates: 'Delegati al Consenso / Candidati'
home.stats.candidates: 共识代表/候选人
```

**Comment by raullenchai** [comment]
Good catch, let's just call it "Delegates" in different languages and remove the prev "something/something" format.

**Comment by liaojikunwork** [comment]
Could you send me "Delegates" in different languages?

**Comment by raullenchai** [comment]
Use google translate pls
