### ISSUE TITLE
send data field is not captured

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1396]
just tried send a tx with data. it does not show up  in action history.

![image](https://user-images.githubusercontent.com/448293/88094360-48f01980-cb48-11ea-8e86-9172062fcc69.png)

https://iotexscan.io/action/dc95edeabdad449b0a49530a8fcb64a30f141cc3168a131b12452d5847569a26

**Comment by guo** [comment]
it used a hex format of an ascii text “text!" here.

**Comment by liaojikunwork** [comment]
I tried a transaction on Desktop Wallet with hex data, but I can't get it as payload
I am wondering if this issue is related to backend

**Comment by raullenchai** [comment]
I tried this morning - https://www.iotexscan.io/action/239b6da575fa3cff16232df296f14c6be1c6de192c6ed8eea66831cc6250a828

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-07-21 at 11 21 40 PM](https://user-images.githubusercontent.com/34900782/88130597-f1ce6100-cba8-11ea-8b1f-e41a7d4aa341.png)

`Data` field should be shown, right?

**Comment by raullenchai** [comment]
yes, without 0x I think

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-07-21 at 11 26 03 PM](https://user-images.githubusercontent.com/34900782/88130806-7b7e2e80-cba9-11ea-84d1-48bcb7bd0db4.png)

The placeholder is `0x1234`
I think it's related to backend, anyway I will check again.

**Comment by raullenchai** [comment]
Good finding, if `0x1234` doesn't work while `1234` works, we shall change the placeholder
