### ISSUE TITLE
[feat]  show erc20 detail  on sign request modal

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-explorer#1400]
![image](https://user-images.githubusercontent.com/12439992/88145896-baee5e80-cc2d-11ea-82a1-a3c150f25671.png)

**Comment by liaojikunwork** [comment]
Hi @uu-z  What details should I show more?

**Comment by uu-z** [comment]
> Hi @uu-z What details should I show more?

hi @liaojikunwork This feature has not been fully considered. I think it’s a little bit difficult to implement at present. let me turn it off first and then reopen it in the future.
