### ISSUE TITLE
"About IoPay" menu item not showing info dialog

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1434]
![photo_2020-07-30_11-34-34](https://user-images.githubusercontent.com/11096047/88909690-bc3a0f80-d25b-11ea-956b-f0cb4965b3db.jpg)

**Comment by liaojikunwork** [comment]
@raullenchai , should I check on Windows?
I don't have Windows computer

**Comment by liaojikunwork** [comment]
https://www.electronjs.org/docs/api/menu-item#roles
https://github.com/electron/electron/issues/10153

I should create "About IoPay" dialog

**Comment by raullenchai** [comment]
> https://www.electronjs.org/docs/api/menu-item#roles
> [electron/electron#10153](https://github.com/electron/electron/issues/10153)
> 
> I should create "About IoPay" dialog

Sounds good
