### ISSUE TITLE
tx page did not display bytecode

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-explorer#1451]
1. "View more" is no longer there. We used to use it to see contract call data payload (and bytecode in case of contract deploy)

2. also it seems the type of tx (Transfer, Contract, Staking, etc.) and receipt is gone as well? feel those are also useful info of the tx

**Comment by guo** [comment]
it is related to the UTF-8 or hex display. the bytecode section is missing

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-04 at 8 43 43 PM](https://user-images.githubusercontent.com/34900782/89361531-88b31700-d699-11ea-854c-65d513a880c8.png)
![Screen Shot 2020-08-04 at 8 43 52 PM](https://user-images.githubusercontent.com/34900782/89361536-8c469e00-d699-11ea-99ad-726440f3a106.png)
![Screen Shot 2020-08-04 at 8 45 19 PM](https://user-images.githubusercontent.com/34900782/89361538-8cdf3480-d699-11ea-9cf2-2d3add3fabf9.png)

@hunglmtb , I fixed that issue above, but I was getting another issue.
Pls check my screenshots.
