### ISSUE TITLE
number of action chart seems always show a drop because the moving average 

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1531]
![image](https://user-images.githubusercontent.com/448293/89748082-59741f80-da76-11ea-9c6a-c3a1cdbe298b.png)

see how can calculate the moving average to avoid the drop at the end.

**Comment by liaojikunwork** [comment]
@guo , how do you calculate the moving average field on the backend?

**Comment by guo** [comment]
just assume the missing part as the avg.

**Comment by liaojikunwork** [comment]
What about hiding day1? (08-08)

**Comment by liaojikunwork** [comment]
At this moment, hide the day1.
Need to check later again.

**Comment by guo** [comment]
close for now.
