### ISSUE TITLE
NFT updates

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1537]
[] add NFT token to action detail page.
https://iotexscan.io/action/8b536ff5eb4f751d402585824bdc4345ba2d7cd583743d1d54b7698fd24938e2
![image](https://user-images.githubusercontent.com/448293/89763109-af60bb80-daa6-11ea-9426-eac7831e0851.png)

[] add NFT actions to account detail page
such as 
https://iotexscan.io/address/io1xpvzahnl4h46f9ea6u03ec2hkusrzu020th8xx
![image](https://user-images.githubusercontent.com/448293/89763155-cb645d00-daa6-11ea-915d-d214804c9e12.png)

**Comment by newyear6565** [comment]
actions to account：

query {
  xrc721{
 byAddress(address:"io1dcmm002wa0sgt0u7h76pz42r6y4kp37xwsu5zw", numPerPage:10,page:0) {
      exist
      count
      xrc721{
        contract
        hash
        timestamp
        from
        to
        quantity
      }
      }
    }
}
