### ISSUE TITLE
payload is still missing

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1559]
![image](https://user-images.githubusercontent.com/448293/90287447-c566d700-de2c-11ea-8686-72ee8fee6874.png)

https://testnet.iotexscan.io/action/592d43eddd16cdac4210b6e2f9558f458ed8aa22af180fbcb77f19011948aaf1

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-15 at 8 32 24 AM](https://user-images.githubusercontent.com/34900782/90312363-e59ca180-ded1-11ea-8394-2f7e9bea8e03.png)

Payload of that action is empty, so it's not an issue
