### ISSUE TITLE
Cannot deploy contract in ioPay Desktop v1.0.5

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-explorer#1562]
Reproduce steps:
1. Open ioPay desktop v1.0.5
2. Login an account
3. Go to Smart Contracts tab
4. Click "Deploy Contract"
5. Input some "Byte Code"
6. Click "Sign Action"
7. Click "Yes, make action"
Observe no response

**Comment by guo** [comment]
@CoderZhi give an example here?

**Comment by hunglmtb** [comment]
return error when the low gas limit in antenna
```
ErrUnknown

send action error: {"code":13,"message":"failed to verify action signature: insufficient gas: Insufficient balance for gas","metadata":{"content-length":"0","content-type":"application/grpc-web-text+proto","grpc-message":"failed to verify action signature: insufficient gas: Insufficient balance for gas","grpc-status":"13"}}
```
Could you add the new error code for this case or the message text can be parsed or extracted to make display to user friendly? @ququzone

**Comment by hunglmtb** [comment]
for test https://github.com/iotexproject/IOTX-token-contracts/tree/master/build

**Comment by guo** [comment]
still need a further PR to split the error msg.
