### ISSUE TITLE
text update

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1563]
![image](https://user-images.githubusercontent.com/448293/90294079-6dcf6800-de3a-11ea-8e05-9fe705c9a9d9.png)

a few seconds ago -> just now 
to save space.

**Comment by liaojikunwork** [comment]
Where can I see that?
Can't find it

**Comment by guo** [comment]
right bottom section of front page.

**Comment by guo** [comment]
i just did a search. it is not very trivial fix. let close for now.
