### ISSUE TITLE
Send new after deploy a contract open up a dialog with NaN

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1580]
![image](https://user-images.githubusercontent.com/448293/90562153-9adf8b80-e156-11ea-9470-e19d087e27b3.png)

It should go back to the action tab or contract tab. 

We can simply call the button "Complete" and goes back to the front page of certain tab.

**Comment by liaojikunwork** [comment]
Could you share a sample ABI for testing? @guo

**Comment by liaojikunwork** [comment]
@guo, Should I change "Yes, make action" to "complete"? To stop "send new" after deploying a contract?
