### ISSUE TITLE
XRC20 transfer to address should link to /address/ioxxx. now link to /actoin/ioxxxx

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1588]
![image](https://user-images.githubusercontent.com/448293/91155919-54b78a00-e678-11ea-9275-113e5e2d6197.png)

**Comment by liaojikunwork** [comment]
@guo  Could you share the exact action link?

**Comment by guo** [comment]
https://testnet.iotexscan.io/action/457cc17335d956cbb0af021a86a3b3397589ccd37a1d3261ad6fbcf0678995ba
