### ISSUE TITLE
iopay desktop - layout issue

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1593]
![image](https://user-images.githubusercontent.com/448293/91341558-8589e300-e78e-11ea-969a-ce0e46456b8a.png)

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-27 at 8 42 08 AM](https://user-images.githubusercontent.com/34900782/91443318-2c2ebc00-e841-11ea-8fc5-ac4da8f9ba8e.png)

I can't see those issues on my side

**Comment by guo** [comment]
iopay desktop only issue? or add a new token?

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-27 at 1 22 41 PM](https://user-images.githubusercontent.com/34900782/91474556-61023980-e868-11ea-904e-efb2e57349be.png)

May I show a scroll in this case? @guo

**Comment by guo** [comment]
you can make the wallet a bit wider I think. now it is kinda narrow.
