### ISSUE TITLE
iopay desktop style change 

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1617]
![image](https://user-images.githubusercontent.com/448293/92316138-19d12280-efa5-11ea-925f-113cdfc562e2.png)

**Comment by ZQ-jhon** [comment]
![a](https://user-images.githubusercontent.com/26297704/93347262-72d36d00-f867-11ea-954d-3627a4103f12.gif)
@guo  
reduce padding-left & padding-right, and reset the label and input width.
