### ISSUE TITLE
IoPay Login not working when it's on a Ledger account

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1622]
**Reproduce**
- Unlock IoPay with a **Ledger**
- Go to https://member.iotex.io/profile/
- Click on "**Login or Sign Up with IoPay**" button

=> in the "**Sign Message**" IoPay popup clicking "**Yes, Make action**" does nothing

**Comment by guo** [comment]
fixed on iopay side. but requires a new ledger iotex app to support.

**Comment by simonerom** [comment]
The latest IoTeX app for Ledger v0.1.7 now allows signing messages, so this is fixed now.
