### ISSUE TITLE
number of token holders pagination is not correct

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1633]
![image](https://user-images.githubusercontent.com/448293/93554274-fd2fd580-f928-11ea-9de9-d181cb44f291.png)

**Comment by ququzone** [comment]
when page 15 is clicked, there is no API requests, I think this is pagination component bug.

**Comment by blesstosam** [comment]
the reason why page 15 is empty is that this query api only return 200 data：
<img width="1434" alt="WX20200926-102952@2x" src="https://user-images.githubusercontent.com/26403700/94328347-5e6c3e80-ffe4-11ea-8681-1812715826a9.png">

and the query api does not have `pagination` params, so need to add a `pagination` to this api
```
query tokenHolders($tokenAddress: String!) {
    xrc20 {
      tokenHolderAddresses(tokenAddress: $tokenAddress) {
        addresses
        count
      }
    }
  }
```
