### ISSUE TITLE
cross-env pkg blocked iopay desktop build

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1637]
it was fixed by adding cross-dev to packages. https://github.com/iotexproject/iotex-explorer/commit/b3d2bdcd9f4098df9de7d0dd269c4ce9a5935aaa

but it seems only needed in dev mode. 

todo here: see how to remove the dep from production build of iopay desktop.

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/93654784-45f09880-f9d4-11ea-82e4-47da3d63fd1a.png)

**Comment by guo** [comment]
still not able to build.

**Comment by guo** [comment]
also removed `cross-env` in electron build: 
https://github.com/iotexproject/iotex-explorer/commit/d4e48c32f4f9150881ed6dc991cf4a1abe4866ee

**Comment by ZQ-jhon** [comment]
> still not able to build.

try replace `cross-env`  to `npx cross-env xxx`
