### ISSUE TITLE
Failed to query actions by actionType = execution/grantReward/transfer

### ISSUE THREAD

**Issue by anshuomomo** [iotexproject/iotex-explorer#1641]
https://iotexscan.io/action?actionType=grantReward
https://iotexscan.io/action?actionType=execution
https://iotexscan.io/action?actionType=transfer

![image](https://user-images.githubusercontent.com/16026265/93750210-b514f980-fc2d-11ea-9f4d-8926d2e538b4.png)

**Comment by uu-z** [comment]
refer: https://github.com/iotexproject/iotex-analytics/issues/292#issue-694260290
