### ISSUE TITLE
support multiple token transfer

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1669]
![image](https://user-images.githubusercontent.com/448293/95260575-d0f7ce00-07dd-11eb-89ca-1784c0197b98.png)

https://alpha.iotexscan.io/action/3016916fd3110d4f28861c882097875ca6e1261a46849e4ea90e0fd11737e713

**Comment by guo** [comment]
this example too: https://www.iotexscan.io/action/98173b50d0150e8b025446f469bc3036917726f5faac670d4de0d612cf8b42ca

vita claim

**Comment by hunglmtb** [comment]
it's using the query from analytics to display the token transfer list, then seems to need support from analytics for display correctly token value. if we can do it in front-end by action hash or log, pls help how to parse or decode action info
```
query {
    action {
      byHash(actHash: "${hash}") {
        evmTransfers {
          from
          to
          quantity
        }
      }
    }
  }
```

![image](https://user-images.githubusercontent.com/11267061/95420894-79d13500-0966-11eb-9aad-d6598a3e09df.png)

**Comment by hunglmtb** [comment]
@ququzone could u take a look too?

**Comment by guo** [comment]
possible to use logs? @CoderZhi

**Comment by CoderZhi** [comment]
![image](https://user-images.githubusercontent.com/35643171/96045126-61f62700-0e26-11eb-8d39-940f8cc7dd0e.png)

@hunglmtb it will be very heavy for the analytics service to decode and store all the events. Instead, you can decode the logs directly in the front end.
So, the front-end needs to have a list of tokens (addresses) and the corresponding "topics", which will be shown here. For example, token "io14nhfkywdfvl40evgsqnh43ev33q6he8yez8c8a" is the address of interest, and "ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" is the topic we want to decode and show, "000000000000000000000000852a7337245d057e63d7c50752358c7b5a0f4ad4" is the sender address, "000000000000000000000000fbb059f39140a32dea90f72a4fb9c4e26350980a" is the recipient address, and "00000000000000000000000000000000000000000000001b03479a8b1c722aa7" is the amount.

**Comment by hunglmtb** [comment]
I tried to decode, it's okay for the sender, recipient as `address `and data as `uint256 `for the amount, but not success as `string `for topic. Is there any detail here for topic ? @CoderZhi 
I also got topic with 4 items: 
```
"topics": [
      "06239653922ac7bea6aa2b19dc486b9361821d37712eb796adfd38d81de278ca",
      "000000000000000000000000852a7337245d057e63d7c50752358c7b5a0f4ad4",
      "000000000000000000000000000000000000000000000d8a6c0a051bc5340000",
      "00000000000000000000000000000000000000000000001b03479a8b1c722aa7"
    ]
```

`000000000000000000000000000000000000000000000d8a6c0a051bc5340000 ` seems is  `uint256` ? How we should display this topic ? @CoderZhi

**Comment by CoderZhi** [comment]
> I tried to decode, it's okay for the sender, recipient as `address `and data as `uint256 `for the amount, but not success as `string `for topic. Is there any detail here for topic ? @CoderZhi
> I also got topic with 4 items:
> 
> ```
> "topics": [
>       "06239653922ac7bea6aa2b19dc486b9361821d37712eb796adfd38d81de278ca",
>       "000000000000000000000000852a7337245d057e63d7c50752358c7b5a0f4ad4",
>       "000000000000000000000000000000000000000000000d8a6c0a051bc5340000",
>       "00000000000000000000000000000000000000000000001b03479a8b1c722aa7"
>     ]
> ```
> 
> `000000000000000000000000000000000000000000000d8a6c0a051bc5340000 ` seems is `uint256` ? How we should display this topic ? @CoderZhi

    event AddLiquidity(
        address indexed provider,
        uint256 indexed iotx_amount,
        uint256 indexed token_amount
    );
