### ISSUE TITLE
IoPay shows a blank screen on Delegate name registration

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1673]
When registering a new delegate on https://member.iotex.io/profile/name-registration/ then clicking "Submit", copay shows a black page:

![image](https://user-images.githubusercontent.com/11096047/95580506-bd47a400-0a37-11eb-9c86-5e90c1eac1c3.png)

**Comment by ZQ-jhon** [comment]
The error is TypeError when access property that not exist: 
![image](https://user-images.githubusercontent.com/26297704/95675316-ec514780-0be8-11eb-8c59-ac3a616f7db3.png)
