### ISSUE TITLE
Add a new item "BUCKETS" in menu

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-explorer#1684]
![image](https://user-images.githubusercontent.com/35643171/96932513-db6bc600-1473-11eb-96e6-1bf0d3e5216c.png)

Redirect to a new page which list all buckets in details. Each bucket is clickable linked to 'iotexscan.io/bucket/{index}'

**Comment by hunglmtb** [comment]
The #1706 is in a draft that includes a query bucket list and displays some columns. You will need to correct the display of this table of buckets - be used as a share component for task #1689. Pls help to finish this task with the PR then continue #1689 @jianly . Thanks
