### ISSUE TITLE
xrc20 amount display error

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-explorer#1690]
xrc20 amount display error at transfer action page， suggest determine the decimal place according to decimals. 
https://iotexscan.io/action/9fe380a827c906a1afecbf572b6408ef2652bc5de3e746bdc58e041e2070d85a
this action should display `0.00000021 ioWBTC`

<img width="691" alt="" src="https://user-images.githubusercontent.com/455827/98079690-33142380-1eaf-11eb-8dd0-08d48ef25ab0.png">

**Comment by hunglmtb** [comment]
It seems to be format number with 2 digits then it displays 0. Let me fix
