### ISSUE TITLE
Withdraw to Binance Wallet

### ISSUE THREAD

**Issue by AirdropAnalyst** [iotexproject/iotex-explorer#1746]
Withdraw Binance Address:
io1jjxy9l4uepzsa2j6f3ae5s4pxgrvh7py2puc65

https://iotexscan.io/action/3bdc1a5ad1b226d7a88d38571a45fefa0f115d171e0e6280129f95fe1db687c3

Wrong transaction and wrong address. Please give my balance 🙏🙏
Waiting For You replay

**Comment by CoderZhi** [comment]
the issue has been resolved. please check the link again

**Comment by guo** [comment]
Resolved in https://github.com/iotexproject/iotex-explorer/commit/89bd6f1d4ad7b7a25b84a1729655f8947feab2e9
closing
