### ISSUE TITLE
wiotx logo

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#1778]

**Comment by loriIoTeX** [comment]
![wiotx](https://user-images.githubusercontent.com/38968374/109350101-d22ca480-782b-11eb-98f3-025266ae6b62.png)

**Comment by loriIoTeX** [comment]
Smaller size icon:
![wiotx_64*64](https://user-images.githubusercontent.com/38968374/109370354-c73a3a00-7854-11eb-9bf3-15e2a17b2a5d.png)

**Comment by DengMMM** [comment]
![icon_wiotx_64](https://user-images.githubusercontent.com/50934079/109405624-42166880-79ad-11eb-8588-3a3a21bbcb24.png)
![icon_wiotx_512](https://user-images.githubusercontent.com/50934079/109405625-42aeff00-79ad-11eb-8a1c-f882dcf6b1c3.png)
