### ISSUE TITLE
I'm trying to send IOTX to ioPay Desktop wallet using the Account Address under Action History in the wallet and I keep getting an error message that it's an invalid address. Please advise

### ISSUE THREAD

**Issue by pasrkb** [iotexproject/iotex-explorer#1800]

**Comment by pasrkb** [comment]
I am trying to send IOTX to ioPay Desktop wallet using the Account Address under Action History in the wallet and I keep getting an error message that it's an invalid address. Can anyone advise me on this?

**Comment by Joshuavo6** [comment]
having the same issue

**Comment by ThinkingaboutJesusChrist** [comment]
I tried sending IOTX from Coinbase to the ioPay desktop wallet using the Iotex address, and that address was refused.  I then tried the corresponding Web3 address from the Iotex explorer, and that worked, but the ioPay wallet doesn't see the tokens at the Web3 address yet.

**Comment by ThinkingaboutJesusChrist** [comment]
https://community.iotex.io/t/official-ledger-hw-wallet-thread/1132

**Comment by jrynkiew** [comment]
please send to support@iotex.io for help.
