### ISSUE TITLE
Cannot send BUSD-bsc tokens

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1811]
Sending BUSD-bsc from ioPay desktop results in an error: transaction is not broadcast. Sending other tokens like VITA and ioBUSD works well, seems not a gas issue.

![image](https://user-images.githubusercontent.com/11096047/113058675-bd3a8c80-91ae-11eb-8352-bc7639e19bef.png)

**Comment by guo** [comment]
caused by this line
https://github.com/iotexproject/iotex-explorer/blob/ae827d58cbc9d0d58f7ff675c156a14cbb393d26/src/erc20/erc20.ts#L324

the gasInput is not defined. You can debug from here.
