### ISSUE TITLE
ioPay ErrExecutionReverted on each transactions

### ISSUE THREAD

**Issue by nvandamme** [iotexproject/iotex-explorer#1818]
Hi, wether using ioPay Desktop 0.13 or 0.14, begining yesterday,  each of my transanctions is being rejected with an ErrExecutionReverted error using mimo swapping or liquidity pooling. The only transactions being executed correctly are "Approve"'s one.
I've tried to uninstall iopay and reinstalling it, removing iopay cache (User/AppData/Roaming/iopay) to no avail.
One weird thing though is that using iopay on another machine works fine.

**Comment by jrynkiew** [comment]
please send to support@iotex.io for help. Maybe you changed the default gas settings, causing the transactions to get rejected by the blockchain. Also, let us know in your e-mail if you've encountered this problem in the new version
