### ISSUE TITLE
Make iotexscan accept wallet address in Ethereum format

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-explorer#1841]
When people try reaching the explorer page for their wallet in Metamask, it uses the "0x..." format of the address, which in iotexscan just fails.

Can we quickly fix this e.g. by applying the ethereum address conversion at the iotexscan.io/address/<addr> routing level?

I.e. make iotexscan.io work both with 
`https://iotexscan.io/address/io1a8r9fvu6e3vthfaqvnxlhc6eavsm6t8a2cwtud`

and with 

`https://iotexscan.io/address/i0xe9C654b39aCc58bBa7a064cDFBe359EB21Bd2CfD`
(same wallet)

**Comment by anshuomomo** [comment]
https://iotexscan.io/address/0x2eE1d96CB76579e2c64C9BB045443Fb3849491D2
