### ISSUE TITLE
wallet not opening

### ISSUE THREAD

**Issue by gwc4343** [iotexproject/iotex-explorer#1896]
hello, i put in password but wallet doesn't open. it opens to the main page but wallet not opening. see attached file.

![iotex wallet mainpage](https://user-images.githubusercontent.com/37265330/129462846-3c7e7c88-60ce-492f-ad63-11ae4ed82277.PNG)

**Comment by chen-yijiang** [comment]
Sorry, the api visits have been relatively large recently, resulting in slow api visits, you can try more.

**Comment by gwc4343** [comment]
Hello, is IOTX working on this issue? I've attempted numerous times for the last 4-5 days but cannot access my wallet balance or claim my VITA. This shouldn't be happening am I correct. Hopefully there is a solution to this problem and it is being worked on.
