### ISSUE TITLE
Desktop Wallet does not see IOTX tokens at the Web3 address.

### ISSUE THREAD

**Issue by JacobGoin** [iotexproject/iotex-explorer#1911]
I tried sending IOTX from Coinbase to the ioPay desktop wallet using the Iotex address, but that address was refused by Coinbase as invalid.  I then tried the corresponding Web3 address from the Iotex explorer, and that worked; however, the ioPay wallet doesn't see the tokens at the Web3 address yet.

**Comment by ThinkingaboutJesusChrist** [comment]
Dear Developers,
Thank you for your help.

**Comment by maillen** [comment]
I have the same problem

**Comment by ThinkingaboutJesusChrist** [comment]
@maillen I found help for us, but I have not tried it yet.  https://community.iotex.io/t/instructions-depositing-withdrawing-iotx-with-coinbase/3090

**Comment by ThinkingaboutJesusChrist** [comment]
Here is more help: https://community.iotex.io/t/for-those-who-have-issues-withdrawing-iotx-from-coinbase/3216

**Comment by ThinkingaboutJesusChrist** [comment]
And here is a tutorial from iotube.org/faq
Is there a tutorial explaining how to use ioTube?

Yes: check out this ioTube tutorial on the IoTeX community forum: https://community.iotex.io/t/using-iotube-to-move-erc20-tokens-from-ethereum-to-iotex/1452

**Comment by ThinkingaboutJesusChrist** [comment]
Here is help about migrating IOTX ERC-20 tokens to IOTX Mainnet with Ledger Nano:
https://community.iotex.io/t/official-ledger-hw-wallet-thread/1132

**Comment by jrynkiew** [comment]
I am closing this issue, as it is a bit off-topic. This channel of communication is only to report bugs in the code of the product. In your case, this is a bit different, as it's a user error. User error or any other issues issues not directly related to the functioning of this application should be reported by sending an e-mail to support@iotex.io
