### ISSUE TITLE
Cannot use dapps on iotx desktop wallet

### ISSUE THREAD

**Issue by Albertzaw** [iotexproject/iotex-explorer#1916]
Cannot use iotx desktop wallet to connect with zoomswap. Cannot use dapps on iotx desktop wallet

**Comment by jrynkiew** [comment]
This is the incorrect channel to receive this type of support. please send to support@iotex.io for help. I don't know if it's even possible. ioPay mobile uses web3 injection, and the apps you mentioned are meant to be used with Metamask (web3). ioPay Desktop will not support it most likely.
