### ISSUE TITLE
csv export for staking rewards 

### ISSUE THREAD

**Issue by HildeX** [iotexproject/iotex-explorer#1930]
Hi, 

when exporting staking rewards as csv I found, that there is the comma/dot missing so rewards are not calculated properly. Please see attachement. 

Also, using the age format is a real pain, UX wise but also for the export. UX: I have to open every transaction to get the specifi date. Export: csv exports coming in the age format are not usable for accounting tools bc they need a date for the import. 

Can this be switched somewhere in the explorer? If not then it renders the whole export useless and it needs to be changed to date format. Otherwise I have a real problem bc I have to add every reward manually. 

Thanks and kind regards
Erik

![Bildschirmfoto 2021-11-07 um 10 21 46](https://user-images.githubusercontent.com/35634510/140639472-0c8be1e2-16e0-4666-8b6e-a0aff9b91c91.png)
![Bildschirmfoto 2021-11-07 um 10 21 51](https://user-images.githubusercontent.com/35634510/140639473-7e3eb2db-1c8d-48d3-b61e-7c8cd62999a0.png)

**Comment by jrynkiew** [comment]
Hi HildeX,

I just checked, and the new explorer now offers exports in the correct date/time format as well as the comma/dot issue has been corrected
