### ISSUE TITLE
Error on iotx transfer from metamask

### ISSUE THREAD

**Issue by jorgecrypto9** [iotexproject/iotex-explorer#1935]
I transfered 767,099 IOTX  by the bsc from metamask to my binance account with the action hash 8bec2f8f8f2038c5037c1aa7dd19aa6b442632dce80c88a9dda3789e14f86839
but it didnt arrive. Please help.

**Comment by jrynkiew** [comment]
Hi jorgecrypto9 ,

The issue is not with iotex-explorer, but most likely you sent the tokens to the wrong chain. If you need support on this matter, please contact support@iotex.io by e-mail.
