### ISSUE TITLE
Iopay walllet

### ISSUE THREAD

**Issue by roldquin** [iotexproject/iotex-explorer#1942]
I can't log in to my Iopay wallet account, I input my private key but different account is appearing not my main account which has a 17 IOTX balance.

**Comment by virtueorvice** [comment]
I cannot unlock my ioPay desktop wallet either. I log into my account but when i click to see the details, nothing happens.

**Comment by jrynkiew** [comment]
Please send to support@iotex.io for help.

**Comment by jrynkiew** [comment]
Upon first glance, unless you have your original private key stored somewhere, there is nothing we can do to recover that key for you. ioPay does not have a "restore" functionality built in. Sometimes what happens is that people create a new wallet, deposit tokens to it, but forget to write down the private key, and then proceed to close the application. On the next login attempt, they generate a new wallet, and lose access to the old wallet. This is why there is a reminder during wallet creation to backup your private key for that account.
