### ISSUE TITLE
action receipt responsiveness 

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#257]
<img width="1531" alt="Screen Shot 2019-04-10 at 2 52 52 PM" src="https://user-images.githubusercontent.com/1387285/55916159-66da7a80-5ba0-11e9-9e27-3230dfe16f79.png">

fix table width and in the logs field, use JSON.stringify and make it scrollable in x as well

**Comment by athrunsun** [comment]
BTW, `JSON.stringify` is already used for that field.

**Comment by athrunsun** [comment]
JSON in logs field is now pretty printed.
