### ISSUE TITLE
fix action table ts

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#258]
after the backend change https://github.com/iotexproject/iotex-core/issues/998, let bring back the code in iotex-explorer/src/shared/address-details/action-table.tsx

```
    // TODO(tian): https://github.com/iotexproject/iotex-core/issues/998
    // {
    //   title: t("block.timestamp"),
    //   dataIndex: "timestamp",
    //   render(_: string, record: ActionInfo, __: number): JSX.Element {
    //     return <span>{translateFn(get(record, "block.timestamp"))}</span>;
    //   }
    // },
```

**Comment by athrunsun** [comment]
@puncsky I didn't see timestamp field returned for `query getActions($byIndex: GetActionsByIndexRequest)`.

**Comment by athrunsun** [comment]
@puncsky Where are the code changes for issue 998 in iotex-core? I need to know where to add that field and I think I can find some clues in the backend.

**Comment by puncsky** [comment]
please add some more code to https://github.com/iotexproject/iotex-antenna/issues/169

**Comment by athrunsun** [comment]
@puncsky 
Got compile failure: `Cannot find module 'solc'`.

I think `solc` should be put in `dependencies` instead of `devDependencies` in iotex-antenna (it is used in src/contract/contract.ts, which is added yesterday).

**Comment by puncsky** [comment]
use iotex-antenna@0.11.2 then
