### ISSUE TITLE
Enhance convenience for query 

### ISSUE THREAD

**Issue by ququzone** [iotexproject/iotex-explorer#259]
1. List of Actions on address page should sort by time in reverse order
2. Action detail page should add timestamp display

**Comment by puncsky** [comment]
2 is https://github.com/iotexproject/iotex-explorer/issues/258

**Comment by puncsky** [comment]
@anshuomomo please investigate 1 - is it our pagination problem or is it a backend issue?

**Comment by anshuomomo** [comment]
![image](https://user-images.githubusercontent.com/16026265/55958220-b8673000-5c9a-11e9-9053-2342def88ffe.png)

1 - all is the same data repetition

**Comment by puncsky** [comment]
thanks for investigation. i'd leave it to @zjshen14

**Comment by zjshen14** [comment]
In rc9 and plus, we have introduced height into the grant reward action, so that every action will be different and own a different hash.
