### ISSUE TITLE
port solidity to abi and bytes from iotex-explorer v0.1.2

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#265]
```sol
pragma solidity ^0.4.23;

contract RollDice {
  function rollAward(string requestId, address target) public payable returns (uint256) {
    uint256 rollVal = roll(requestId);
    target.transfer(rollVal);
    return rollVal;
  }

  function roll(string requestId) public view returns (uint256) {
    return (bytesToUint(sha256(abi.encodePacked(block.difficulty, requestId, block.timestamp))) % 5) + 1;
  }

  function bytesToUint(bytes32 b) private pure returns (uint256) {
    uint256 number;
    for (uint i = 0; i < b.length; i++) {
      number = number + uint(b[i]) * (2 ** (8 * (b.length - (i + 1))));
    }
    return number;
  }

  event Deposit(
    address indexed _from,
    uint _value
  );

  function deposit() public payable {
    emit Deposit(msg.sender, msg.value);
  }
}
```

go to https://iotex-explorer.herokuapp.com/wallet, click "deploy contract".  Fill in the sol above and then click "generate abi and byte code". Then it will generate abi and byte code.

![Screen Shot 2019-04-12 at 1 12 44 AM](https://user-images.githubusercontent.com/1387285/56022268-207c3d00-5cc0-11e9-82ea-3b0a792ecc82.png)

please port the "generate abi and byte code" functionality from https://github.com/iotexproject/iotex-explorer/blob/contract/src/shared/wallet/contract/deploy.js to the current repo.

to debug, you can either use npm run watch and go to /wallet or use npm run storybook and go to http://localhost:6006/?path=/story/smart-contract--deploy

**Comment by athrunsun** [comment]
Where should I find the corresponding TS types of original flowtyped types in `entities` folder?

**Comment by puncsky** [comment]
just use types in `iotex-antenna` or define by yourself within the file if it is not shared somewhere else.

**Comment by puncsky** [comment]
<img width="568" alt="Screen Shot 2019-04-15 at 2 54 26 PM" src="https://user-images.githubusercontent.com/1387285/56167934-7128ba00-5f8e-11e9-83b4-38f659b80791.png">

**Comment by athrunsun** [comment]
@puncsky The PR is ready for review. The style issue you mentioned here is fixed as well.
