### ISSUE TITLE
text box padding in the contract deployment

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#32]
this is similar to #3 

1. Go to https://subchain.iotexscan.io/wallet 
2. create an account
3. click the contract tab
4. deploy a contract like the below

```
pragma solidity ^0.4.23;

contract SimpleStorage {
    uint storedData;

    function set(uint x) public {
        storedData = x;
    }

    function get() public view returns (uint) {
        return storedData;
    }
}
```

5. you can then see a page like this

<img width="1674" alt="screen shot 2019-01-04 at 3 56 21 pm" src="https://user-images.githubusercontent.com/1387285/50717026-8ca03280-1039-11e9-996c-5ee09381a30a.png">

you can find there two issues with the gray box in the middle

1. there is no padding for the box
2. there is a text overflow to be handled

A good example is

<img width="635" alt="screen shot 2019-01-04 at 4 01 00 pm" src="https://user-images.githubusercontent.com/1387285/50717109-00423f80-103a-11e9-95d3-c136987eb928.png">

**Comment by Fabryprog** [comment]
Hello @puncsky 

Yes the style is a dirty BUT i am thinking that field "Data" is **needless** (is too long and crypted!)

Can i remove it?
