### ISSUE TITLE
Supporting showing UTF-8 string as a payload

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#366]
Now it only show the hex string

<img width="1680" alt="Screen Shot 2019-04-22 at 9 23 30 AM" src="https://user-images.githubusercontent.com/35021395/56511092-919dca80-64e0-11e9-82ad-a707df495cb7.png">

**Comment by liaojikunwork** [comment]
Could you share the link to the above screenshot?
Can't get action with payload.

**Comment by raullenchai** [comment]
This issue is a bit stale but it refers to `action page` like https://www.iotexscan.io/action/000086e6e3034c104025896f8af9d3e313b95957c076b3a5ebe1f42f8af3a8ad

**Comment by liaojikunwork** [comment]
I am still not sure about this.
Should I decode the payload as UTF-8 string?
![Screen Shot 2020-07-19 at 8 41 45 PM](https://user-images.githubusercontent.com/34900782/87889565-3bc81300-ca00-11ea-9296-500a3d0d0389.png)

**Comment by raullenchai** [comment]
An example: https://github.com/decred/dcrdata/issues/635
