### ISSUE TITLE
"Gas Consumed" needs a unit	

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#380]
<img width="529" alt="Screen Shot 2019-04-23 at 4 07 27 PM" src="https://user-images.githubusercontent.com/989846/56621603-f42abf80-65e1-11e9-8c97-bda866c23618.png">

**Comment by puncsky** [comment]
it's probably Rau

**Comment by raullenchai** [comment]
There is some confusion, let me clarify
-gas, gas limit and gas consumed have no unit.
-gas price has the unit (Rau)
-should add "action fee" which is gas consumed x gas price -- the unit can be IOTX

e.g., https://etherscan.io/tx/0xb097a3f2c90a039bfe3bf5b76d32d6bdd280a0b2529360a70280005af8cd7361
