### ISSUE TITLE
Gas Limit has no unit

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#381]
<img width="928" alt="Screen Shot 2019-04-23 at 8 24 03 PM" src="https://user-images.githubusercontent.com/989846/56630316-d0797080-6605-11e9-954a-12b1c2a432d2.png">

**Comment by raullenchai** [comment]
https://www.iotexscan.io/wallet/transfer

**Comment by puncsky** [comment]
isn't `Rau` the unit in the picture?

**Comment by raullenchai** [comment]
Meant to say - gas limit should not have unit.

**Comment by iotask** [comment]
Default gas limit set to 100K
suggestion: implement suggested gas limit by payload size
