### ISSUE TITLE
[master] apply some new wireframe

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#390]
those are not the final design. and we should not follow them literally. Just add functionalities in ant design which we currently have.

![Action Page - wireframe 1 0](https://user-images.githubusercontent.com/1387285/56783887-be810480-67a2-11e9-90f7-a68c73bfd81f.jpg)
![Block page - wireframe 1 1](https://user-images.githubusercontent.com/1387285/56783888-be810480-67a2-11e9-9eac-74b1aaaf1724.jpg)
![Overview Page - wireframe 1 3](https://user-images.githubusercontent.com/1387285/56783890-be810480-67a2-11e9-8787-05c07495198b.jpg)

* add `blocks / block :height / action list / action detail` navigation
* improve action page details 
* improve block page details
* improve home page
    * add block list
    * update stats area

**Comment by puncsky** [comment]
Just to mention analytics:

1. bookkeeper apis
2. productivity
3. accounts: active accounts, rank

**Comment by uu-z** [comment]
## Component
- add blocks / block :height / action list / action detail navigation #395 

## Function

**Comment by lizhefeng** [comment]
Add one more analytic API: GetRewardsByAddressAndEpoch
