### ISSUE TITLE
[new wireframe] improve home page

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-explorer#398]
- add block list
- update stats area

**Comment by uu-z** [comment]
improve home page
- [ ] Latest block list 
- [ ] Latest block list with animation
- [ ] Go back home
- [ ] Search
- [ ]  Delegates list improve

**Comment by uu-z** [comment]
@nmhung1210  Please help with this issue, just need work with the ui improvement.

**Comment by nmhung1210** [comment]
> @nmhung1210 Please help with this issue, just need work with the ui improvement.

 @uu-z, Do we have UI design for this improvement? If not then can you please add more details of what you're expecting for the improvement?

**Comment by uu-z** [comment]
> > @nmhung1210 Please help with this issue, just need work with the ui improvement.
> 
> @uu-z, Do we have UI design for this improvement? If not then can you please add more details of what you're expecting for the improvement?

For UI design you can refer #390 M0 image.

**Comment by nmhung1210** [comment]
> > > @nmhung1210 Please help with this issue, just need work with the ui improvement.
> > 
> > 
> > @uu-z, Do we have UI design for this improvement? If not then can you please add more details of what you're expecting for the improvement?
> 
> For UI design you can refer #390 M0 image.

OK, I'm checking now

**Comment by nmhung1210** [comment]
@uu-z where can I get the new logo asset?  
![image](https://user-images.githubusercontent.com/6645185/56947553-bd135b80-6b57-11e9-9836-5c874710e117.png)

**Comment by uu-z** [comment]
@nmhung1210 you can ignore the top bar ui  and just focus on the part of the above checklist

**Comment by nmhung1210** [comment]
> @nmhung1210 you can ignore the top bar ui and just focus on the part of the above checklist

@uu-z Could you please advice what should we show inside those stats boxes? 
![image](https://user-images.githubusercontent.com/6645185/57011375-8f97e200-6c2b-11e9-95ae-284a2d285c22.png)

**Comment by uu-z** [comment]
@nmhung1210  In addition to Map, the others only show blockchain statistics related to the number, which should be numbers.

**Comment by nmhung1210** [comment]
> @nmhung1210 In addition to Map, the others only show blockchain statistics, which should be numbers.

I just don't sure how to calculate those stats yet. Could you please guide me on how to get those numbers? (Becuase current version only have the TPS number)

**Comment by uu-z** [comment]
@nmhung1210  Sorry for not explaining clearly. Those number fields are not available yet. You can refer #399  and fill with mock data . For the Map box, because the ui design is not finished yet. You can just ignore it or just place a placeholder block

**Comment by nmhung1210** [comment]
> @nmhung1210 Sorry for not explaining clearly. Those number fields are not available yet. You can refer #399 and fill with mock data . For the Map box, because the ui design is not finished yet. You can just ignore it or just place a placeholder block

ok, thank you for your explanation. I'll use mock data and leave the map box as a placeholder for now.

**Comment by nmhung1210** [comment]
Closed in favor of #487
