### ISSUE TITLE
Transfer detail is wrong!

### ISSUE THREAD

**Issue by Fabryprog** [iotexproject/iotex-explorer#41]
I send this transfer to partecipate "CES 2019 LED Context"
https://iotexscan.io/transfers/1cdb06256042a94bcef0074c53236a6f6ee2a60f955e33d6433ef6ac8ffad512

On details i clicked into "recipient" field but my transfer isn't into **List of Transfers**!!!

https://iotexscan.io/address/io1qyqsqqqqdjqgzp2h0ffzwmkcglvm25c2ac0xmnelwd7kvy

Did we lost table pagination? There is a similar bug  #1 ?!?!?!

**Comment by Fabryprog** [comment]
Note... i use curl to reproduce the bug:

```
curl 'https://iotexscan.io/api/getAddressTransfersId' -H 'origin: https://iotexscan.io' -H 'x-csrf-token: undefined' -H 'accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7' -H 'user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'referer: https://iotexscan.io/address/io1qyqsqqqqdjqgzp2h0ffzwmkcglvm25c2ac0xmnelwd7kvy' -H 'authority: iotexscan.io' -H 'cookie: __cfduid=d4ff1da09ce31379c815ea11e63cb66c31546884406; _ga=GA1.2.2143791961.1546884410; _gid=GA1.2.988531478.1546884410; consent=true; consent.sig=jUIwbiZ3y4s5bYtkhwwTNCN9xss' --data-binary '{"id":"io1qyqsqqqqdjqgzp2h0ffzwmkcglvm25c2ac0xmnelwd7kvy","offset":0,"count":10}' --compressed 
```

The output are very strange:

- request with offset 0, count 10 return 8 rows
- request with offset 0, count 20 return 12 rows
- request with offset 0, count 30 return 22 rows

**Comment by xiaxiangzhou** [comment]
Those link did not reproduce, let's wait for another bug report
