### ISSUE TITLE
Transfer with desktop wallet

### ISSUE THREAD

**Issue by iotask** [iotexproject/iotex-explorer#447]
- Ubuntu 18.04.2 LTS
- Steps:
   - Input "Recipient address", "Amount"
   - Use default "Gas price" and "Gas limit"
   - Send transaction
- Issue:
  - After confirmation dialog it returns to main screen, no error messages but "send transaction" button icon keeps reloading...
   - Transaction don't go through

![image](https://user-images.githubusercontent.com/48599627/57112726-a74c9480-6d17-11e9-9996-b688c53c0c14.png)

**Comment by iotask** [comment]
Tested with different gas price and gas limit, same issue.

**Comment by puncsky** [comment]
this is a good catch - the network provider is localhost in that case because I built it in development mode :P 

sorry for the inconvenience.
