### ISSUE TITLE
[new ui] improve home page v2.0

### ISSUE THREAD

**Issue by uu-z** [iotexproject/iotex-explorer#487]
zeplin page: https://zpl.io/amdkz4e
design elements: [OverviewPage.zip](https://github.com/iotexproject/iotex-explorer/files/3162453/OverviewPage.zip)

![WX20190509-222807](https://user-images.githubusercontent.com/12439992/57461521-c44e0e00-72a9-11e9-9338-c078ffb00f94.png)

**Comment by nmhung1210** [comment]
@uu-z could you please help to add me (nmh@iotex.io) to the Zeplin project at https://zpl.io/amdkz4e?

**Comment by puncsky** [comment]
added

**Comment by puncsky** [comment]
this depends on https://github.com/iotexproject/iotex-react-components/issues/97
