### ISSUE TITLE
fuzzy search - add search by address

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#56]
since we can tell from the client side that the input is an address (string starts with `io`), we can redirect to the address directly.

**Comment by Fabryprog** [comment]
@puncsky search service is merged into iotex-core. Can i resolve it using same GetBlockOrActionByHash service?

Direct redirect when it stats with io can be a not a good idea!

**Comment by Fabryprog** [comment]
There are any news?
