### ISSUE TITLE
update the action list page

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#562]
https://app.zeplin.io/project/5c81bede826def625074c12c/screen/5cd79d03cbd69a34a8c73303

<img width="894" alt="Screen Shot 2019-05-21 at 6 23 49 PM" src="https://user-images.githubusercontent.com/1387285/58140812-9e076700-7bf5-11e9-9306-15804e91afc4.png">

**Comment by guo** [comment]
what is the nametag here?
