### ISSUE TITLE
[wallet- transfer] query action_exist_by_hash poll shows lots of error

### ISSUE THREAD

**Issue by anshuomomo** [iotexproject/iotex-explorer#573]
![image](https://user-images.githubusercontent.com/16026265/58265269-e7041a80-7db1-11e9-88ee-6d6f3b4d6e41.png)

**Comment by puncsky** [comment]
I guess we should revert the general handling of the graphql errors and handle those errors in each of those cases. Some should notify, while others should not do anything regarding errors.

**Comment by nmhung1210** [comment]
You're right. However, I think we can keep general handling for the network error. And for GraphQL error, we can bypass the "not exist in DB" error (common case) at the general handling, and keep other kinds of the error to be notifying as general. What do you think?
