### ISSUE TITLE
Mainchain / subchain bug

### ISSUE THREAD

**Issue by Fabryprog** [iotexproject/iotex-explorer#58]
Where i open a detail (transaction or block or so on) and i change to subchain / mainchain the explorer refresh current page with an error (transaction not found).

Does It be preferred redirect to index page?

**Comment by puncsky** [comment]
I cannot reproduce the issue and don't understand why refreshing the page will yield an error... and the fix seems not related to the page and error?

**Comment by Fabryprog** [comment]
You can reproduce it into iotexscan.io

Open dashboard, trandaction list and transaction detail. Click to subchain (it will open a new window with transaction list )

If you open another section it is the same. It will open always transaction list.

So... i thinks it is so good open ALWAYS a main dashboard! I delete path car and open always main page

**Comment by Fabryprog** [comment]
Right... i cannot riproduce "transaction not found"... it is so crazy...
