### ISSUE TITLE
fix footer subscribe to sendgrid 

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#602]

**Comment by blesstosam** [comment]
@sxlwar could you apply a sendgrid apikey from https://signup.sendgrid.com

**Comment by sxlwar** [comment]
@blesstosam I have registered before. I am confused that it keeps reminding me authorized error when login.

**Comment by blesstosam** [comment]
@sxlwar but i can not see api key in any files, could you send the api key to me  and let me try to fix it, or you can just tell me how to register a api key(i tried on https://signup.sendgrid.com but failed)

**Comment by sxlwar** [comment]
@blesstosam You need to create one by yourself. 

![image](https://user-images.githubusercontent.com/20088392/59149263-ee7c2280-8a45-11e9-9066-dabb36725f39.png)

I just registered a new one and it worked in my own project.

**Comment by blesstosam** [comment]
so you can add the key to project iotex-explorer , see if it can work ?

**Comment by sxlwar** [comment]
@blesstosam I have add it to branch [sendgrid](https://github.com/iotexproject/iotex-explorer/tree/sendgrid).

 It report this error now:
![image](https://user-images.githubusercontent.com/20088392/59764252-ff425900-92cd-11e9-85fd-91271dbed7dd.png)

May be made a stupid mistake somewhere, could you check it ?

sendgrid client documentation is [here](https://github.com/sendgrid/sendgrid-nodejs/blob/master/packages/client/USAGE.md#contactdb)
