### ISSUE TITLE
[Wallet] add copy bytecode link 

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#610]
![image](https://user-images.githubusercontent.com/448293/58496097-ba824100-81ab-11e9-9a88-6755997e2240.png)

**Comment by guo** [comment]
https://testnet.iotexscan.io/wallet/smart-contract/interact

**Comment by uu-z** [comment]
@guo The bytecode here is contract’s bytecode or each function’s bytecode?

**Comment by guo** [comment]
bytecode for this call.
