### ISSUE TITLE
add legend for "delegates"

### ISSUE THREAD

**Issue by loriIoTeX** [iotexproject/iotex-explorer#611]
![image](https://user-images.githubusercontent.com/38968374/58353935-bf9a6580-7e24-11e9-8e93-bc21123a64d2.png)
![icon_ConsensusDelegates_small](https://user-images.githubusercontent.com/38968374/58505766-8d4d7880-8142-11e9-85c9-4ecdde76eb89.png)
![icon_Delegates](https://user-images.githubusercontent.com/38968374/58505767-8d4d7880-8142-11e9-8219-904c79ca4487.png)

Design: https://zpl.io/amdkz4e

**Comment by loriIoTeX** [comment]
[icon_Delegates.zip](https://github.com/iotexproject/iotex-explorer/files/3229333/icon_Delegates.zip)

**Comment by puncsky** [comment]
the category field of those orange entries is 

```
DELEGATE_CANDIDATE
```

**Comment by sxlwar** [comment]
correspond to [this pr](https://github.com/iotexproject/iotex-react-components/pull/123)
