### ISSUE TITLE
delegate list show productivity error

### ISSUE THREAD

**Issue by anshuomomo** [iotexproject/iotex-explorer#617]
![image](https://user-images.githubusercontent.com/16026265/58521667-c5f75b80-81ef-11e9-8814-8981f6e42ca8.png)

the same delegates in [meber.iotex.io](http://member.iotex.io) 

![image](https://user-images.githubusercontent.com/16026265/58521677-d27bb400-81ef-11e9-91ac-826bf1c50c99.png)

**Comment by puncsky** [comment]
cannot reproduce
