### ISSUE TITLE
Execution page doesn't display execution correctly

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#652]
https://testnet.iotexscan.io/action/26f776cf89bc0a091fde0458d1d5a7ffdd12fd22f84e4bd0f376ce93530809d1

**Comment by puncsky** [comment]
![Screen Shot 2019-06-06 at 2 40 14 PM](https://user-images.githubusercontent.com/1387285/59138376-96f48e80-8941-11e9-94f6-7fb75c14c3e6.png)


data = "10f5a5c000000000000000000000000023684c7e4c9a8a67f9ad24cc19650aa2b8863df8"
method = undefined, data = "10f5a5c000000000000000000000000023684c7e4c9a8a67f9ad24cc19650aa2b8863df8"
method


<img width="637" alt="Screen Shot 2019-06-07 at 4 31 55 PM" src="https://user-images.githubusercontent.com/1387285/59138410-c99e8700-8941-11e9-9343-38fb0fc369ea.png">
