### ISSUE TITLE
Add a refresh button on balance tab

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-explorer#680]
![image](https://user-images.githubusercontent.com/35643171/59216694-fab0ce80-8b70-11e9-9670-8d32d00e33c2.png)

If the wallet page is refreshed, user will be asked to input private key again. Thus, we need to add a button for force refresh all balances or one balance

**Comment by puncsky** [comment]
if the interval is short enough, we do not need the refresh button.
