### ISSUE TITLE
Replace address to the accordance delegate name

### ISSUE THREAD

**Issue by loriIoTeX** [iotexproject/iotex-explorer#681]
![image](https://user-images.githubusercontent.com/38968374/59217187-3ac48100-8b72-11e9-84c5-0c9aab82d25e.png)

**Comment by raullenchai** [comment]
this has high priority

**Comment by puncsky** [comment]
in web-bp, add a query by ioOperatorAddress https://github.com/iotexproject/web-bp/blob/82a8221992c68eb5b4d6321d1accb722738878a0/src/api-gateway/api-gateway.graphql#L310

and query it in the blocklist
