### ISSUE TITLE
Add "Claim" Button to VITA 

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#698]
![image](https://user-images.githubusercontent.com/448293/59426953-1683d100-8e0c-11e9-85a6-241450b6bb0f.png)

**Comment by nmhung1210** [comment]
Can you please explain what does Claim button do?

**Comment by guo** [comment]
claim button to call claim function, smart contract with ABI: https://gist.github.com/guo/cd0a649fdf30f5ba6ef4998e3cdaf879

Discord link: https://discord.gg/4z3BTcd

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/59452994-882a4200-8e41-11e9-9dc2-3672ae486e3a.png)

**Comment by guo** [comment]
confirm dialog after clicking Claim.
![image](https://user-images.githubusercontent.com/448293/59567339-3aab1080-909f-11e9-930b-1e3e691cd210.png)

**Comment by guo** [comment]
The next step is result page:
![image](https://user-images.githubusercontent.com/448293/59567348-58787580-909f-11e9-84eb-a4b0aa7e38f8.png)

**Comment by nmhung1210** [comment]
![image](https://user-images.githubusercontent.com/6645185/59567389-91145100-9097-11e9-9e4b-57ac3ac8565b.png)
