### ISSUE TITLE
change in add custom token dialog

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#699]
![image](https://user-images.githubusercontent.com/448293/59427325-f86aa080-8e0c-11e9-9f04-c6b4e045875e.png)

**Comment by guo** [comment]
for testnet: VITA's address is io1y9ndaezjrdlkw93hquqru7txh9jcsmtmrvt4yw. 
for production. it is not there yet.

**Comment by nmhung1210** [comment]
we have 2 address for the VITA in testnet: io1hy9w96v7gz7mqquyyacfhtqn6r0yasnsqrjk9h and io1y9ndaezjrdlkw93hquqru7txh9jcsmtmrvt4yw
Which one should be used?

**Comment by nmhung1210** [comment]
Ref. ![Screen Shot 2019-06-14 at 12 11 56 AM](https://user-images.githubusercontent.com/6645185/59452959-151ccd80-8e39-11e9-8888-79c382a547cc.png)
