### ISSUE TITLE
remove data field when switching to VITA

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#701]
![image](https://user-images.githubusercontent.com/448293/59427692-d9b8d980-8e0d-11e9-90a5-c4a7071a4f9e.png)

![image](https://user-images.githubusercontent.com/448293/59427637-b726c080-8e0d-11e9-8aae-8cac9e858cfa.png)

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/59427667-cf96db00-8e0d-11e9-8019-f2555758d2aa.png)

**Comment by guo** [comment]
use unit in the confirm dialog.

![image](https://user-images.githubusercontent.com/448293/59427962-809d7580-8e0e-11e9-9d7c-be1178e23752.png)

**Comment by sxlwar** [comment]
the data field has been restricted in #690 

![image](https://user-images.githubusercontent.com/20088392/59483950-61502800-8ea2-11e9-9d04-d582e8bee5f1.png)
