### ISSUE TITLE
Make "gas limit" and "gas price" editable

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-explorer#728]
![image](https://user-images.githubusercontent.com/35643171/59633755-159bb980-9102-11e9-874f-ee07d342c2ea.png)

User may want to set customized gas limit or gas price.

**Comment by nmhung1210** [comment]
User can edit them by pressing on the No, cancel button and then modify the transaction.

**Comment by CoderZhi** [comment]
Not always true. For example, if user clicks "Claim", and wants to increase gas price or gas limit, by clicking "No, cancel" won't provide the user any place to change them.

**Comment by nmhung1210** [comment]
> Not always true. For example, if user clicks "Claim", and wants to increase gas price or gas limit, by clicking "No, cancel" won't provide the user any place to change them.

This is the confirmation dialog. If user press on the "No, cancel" then they will navigate back to the previous editable form. 
It will produce confusing if something editable here. Do we need another confirmation dialog for those editable values?

**Comment by nmhung1210** [comment]
Closed due to no response.
