### ISSUE TITLE
Error in claiming.

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#738]
![image](https://user-images.githubusercontent.com/448293/59672728-9c2fc400-91f2-11e9-86ba-a8f4c2b09829.png)

msg:
https://justpaste.it/7qwa6

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/59673443-e9f8fc00-91f3-11e9-8382-57feb40586d6.png)

**Comment by nmhung1210** [comment]
GAS Limit issue. Will be fixed by #740
