### ISSUE TITLE
[error] v1.0 graphql

### ISSUE THREAD

**Issue by hunglmtb** [iotexproject/iotex-explorer#74]
running from v1.0 with error suddenly
`Error! GraphQL error: 14 UNAVAILABLE: channel is in state TRANSIENT_FAILURE`

**Comment by puncsky** [comment]
this is antenna error - isn't 35.203.158.71:14014 working?

**Comment by hunglmtb** [comment]
It working now at `35.230.103.170:10000`.
Thanks
