### ISSUE TITLE
Disable "Generate" button

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-explorer#742]
![image](https://user-images.githubusercontent.com/35643171/59714218-f9f9e700-91c5-11e9-9ec5-81e0db747d72.png)
Two options:
1. Hide Generate button after click
2. Disable Generate button until user changes Nonce

**Comment by puncsky** [comment]
the feature is located at https://iotexscan.io/dev/wallet claim button

**Comment by raullenchai** [comment]
Should we close it then @CoderZhi @puncsky

**Comment by gyanpgupta** [comment]
I already created the PR and its merged into the master https://github.com/iotexproject/iotex-explorer/pull/759
