### ISSUE TITLE
update join discord and claim button styles

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#747]
<img width="568" alt="Screen Shot 2019-06-18 at 4 30 00 PM" src="https://user-images.githubusercontent.com/1387285/59726406-5a008580-91e6-11e9-88cb-9fed9c009aa4.png">

update join discord button to `type="link" `
update the claim button to non primary

**Comment by nmhung1210** [comment]
Closed via [#1cdebee](https://github.com/iotexproject/iotex-explorer/commit/1cdebee2bb158daa83fd3c3b842a1cc3cd630daf)
