### ISSUE TITLE
Lower the gas limit required for claim to 150,000

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#752]
1 Million gas limit is too high, the account with lower than 1 IOTX balance will not able to claim because the action will be rejected by action pool immediately.

<img width="1244" alt="Screen Shot 2019-06-19 at 11 24 32 AM" src="https://user-images.githubusercontent.com/35021395/59791060-24ab7480-9286-11e9-8fe4-530221a318d3.png">

**Comment by raullenchai** [comment]
https://www.iotexscan.io/action/cb6a04423131dc4372c0406b32f92665f4e6e210bd5518d9824df2ef08d932cc  suggests 100000 gas should do the work.

**Comment by zjshen14** [comment]
<img width="769" alt="Screen Shot 2019-06-20 at 4 44 52 PM" src="https://user-images.githubusercontent.com/35021395/59888092-d9bf5900-937a-11e9-8106-4f7d46ca1ec3.png">
