### ISSUE TITLE
transfer vita failed using web wallet

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#767]
https://www.iotexscan.io/action/d1b0f76167c702d076b5770f61f784aa68fe1eacc2ba4b25515c7c268ce97a7b

**Comment by raullenchai** [comment]
Tried from web wallet and it went through https://www.iotexscan.io/action/f5ebb21f27a82ef30c550e599862661dd0ade28cf6ef7da2b796727e7ba086f0

**Comment by raullenchai** [comment]
This is the roundup problem introduced by the frontend -- when transferring this account has 226703.202368911... VITA while it intended to transfer 226703.202369. Backend does the right thing.

**Comment by guo** [comment]
need to round down, no round up

**Comment by puncsky** [comment]
fixed in https://github.com/iotexproject/iotex-explorer/commit/e61d0679b964d070ec3102a8c8273be662f3fa02
