### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [iotexproject/iotex-explorer#781]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/iotexproject/iotex-explorer/blob/master/package.json#L166

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by puncsky** [comment]
thanks for reporting the issue.
