### ISSUE TITLE
bidding gas limit too low

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-explorer#787]
![image](https://user-images.githubusercontent.com/35643171/60276929-6c975080-98b1-11e9-8703-9cc19be98117.png)

Must be higher than 60,000. Let's set it to 100,000

**Comment by puncsky** [comment]
let's fix it along with claim and claimAs

probably with fixed price 

claim: 100000
claimAs: 200000
bid: 100000

**Comment by nmhung1210** [comment]
Fixed via #789
