### ISSUE TITLE
action hash not found should not be 404

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#795]
we should show a page similar to action hash page. show action hash not found in side the page. The current 404 page is a bit misleading. it is actually action hash not found, not the page not found. 

![image](https://user-images.githubusercontent.com/448293/60395914-0b030a80-9b6d-11e9-8d35-00e3ad91133b.png)

**Comment by DengMMM** [comment]
![404](https://user-images.githubusercontent.com/50934079/60397178-b8c9e580-9b7c-11e9-8209-75cc8cc66252.png)
