### ISSUE TITLE
Change texts on https://member.iotex.io/profile/claim-rewards/

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#801]
![Screen Shot 2019-07-01 at 2 02 05 PM](https://user-images.githubusercontent.com/989846/60466567-d80e5480-9c08-11e9-818a-43892be1b5d5.png)

"Claim IOTX" => "Claimable IOTX"
"Available Credits" => "Claimable IOTX"
"Credits to Claim" => "IOTX To Claim"
"Claim Credit" button => "Claim" button

**Comment by gyanpgupta** [comment]
@raullenchai  I do not found this in iotex-explorer is this in the different Repository?

**Comment by raullenchai** [comment]
Added you to web-bp repo. Please re-file this issue there and fix it. Close this one for now.
