### ISSUE TITLE
Swap IOTX to IOTX-E

### ISSUE THREAD

**Issue by DanyAC** [iotexproject/iotex-explorer#802]
When trying to swap  IOTX to IOTX-E using the tool (https://member.iotex.io/tools/ERC-20), in google chrome a new tab open but doesn't work (says Open "URL:iopay"), in firefox is trying to open the wallet but  the following error appears:

![image](https://user-images.githubusercontent.com/14945789/60471824-a616e580-9c3c-11e9-80f3-83685decd7fd.png)

Windows 7, Iotex wallet v0.4.1

**Comment by nmhung1210** [comment]
The error is most likely `out of memory` issue. Can we have the specification of the PC that has this issue?

**Comment by DanyAC** [comment]
Hi!, what kind of specification do you need?

Windows 7 Ultimate - SP1 (64 bits)
AMD Phenom II X4 955 Processor 3.21 GHz
4GB RAM
355GB Free Space

Regards

**Comment by nmhung1210** [comment]
4GB RAM might not enough if you run Windows 7 Ultimate (64 bits) with some apps (like chrome tabs, firefox) at the same time. Can you please try to close other apps and open the wallet again?

**Comment by nmhung1210** [comment]
Closed. Client's PC doesn't have enough memory for multitasks
