### ISSUE TITLE
support /?search=  url which is used in browser address search

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#816]

**Comment by gyanpgupta** [comment]
@guo  could you please add more description thanks

**Comment by nmhung1210** [comment]
@gyanpgupta you might need to handle URLSearchParams for the [search-box](https://github.com/iotexproject/iotex-explorer/blob/93669996086ad09803209f3260d8f08dacce4b67/src/shared/home/search-box.tsx#L18) like below:
![image](https://user-images.githubusercontent.com/6645185/61129468-ac2f8080-a4de-11e9-97b5-2b70431ae35b.png)
