### ISSUE TITLE
Coping address to clipboard not working on mobile

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#826]
![05729421-144D-4EEF-BE6F-72AA68EEDAB2](https://user-images.githubusercontent.com/1387285/60749527-0e710a00-9f50-11e9-9bfe-27eea50e9be7.jpeg)

**Comment by gyanpgupta** [comment]
@puncsky  not reproduced tested on mobile. its working fine on mobile.

**Comment by gyanpgupta** [comment]
@puncsky , could we close this issue if its not reproducible ? thanks

**Comment by puncsky** [comment]
if you are using Android, it may probably work.

However, as you can see in the screenshot. it is iPhone. Please help fix it on iPhone.

**Comment by raullenchai** [comment]
@liaojikunwork pls verify if this is still an issue; if not, pls close

**Comment by liaojikunwork** [comment]
@raullenchai 
It works well on Android, but not working on iOS.
Also, on iOS, the sidemenu and modal are not working (iPhone 6+ and iPhone X)

**Comment by raullenchai** [comment]
Pls help to fix it!

**Comment by guo** [comment]
it seems `antd`'s issue with lower version. however, upgrading to latest version requires a lot of changes in code. assigning to @uu-z to take a look.
