### ISSUE TITLE
Show Total Transactions on the front page

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-explorer#841]
<img width="1420" alt="Screen Shot 2019-07-09 at 10 53 19 PM" src="https://user-images.githubusercontent.com/989846/60943958-5d92a400-a29c-11e9-9723-ce89b3516a76.png">

**Comment by raullenchai** [comment]
cc @puncsky for suggesting how to implement
cc @lizhefeng if backend work is needed
cc @loriIoTeX for design

**Comment by puncsky** [comment]
@gyanpgupta please replace the icon with <Icon type="rise" />.

update the number and texts to total transactions. the gql field is 

```
  chainMeta {
    numActions
  }
```

**Comment by gyanpgupta** [comment]
@puncsky  this is already done by hung.

**Comment by gyanpgupta** [comment]
@raullenchai  @puncsky  can we close it , I think its already done. thanks
