### ISSUE TITLE
[wallet] add translations back and fix electron build

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#845]
when I was trying to release new iotex-wallet, i find that the app was broken after build. so I add linter and removed translations loaded from webpack https://github.com/iotexproject/iotex-explorer/pull/844/files. 

please investigate, fix it, and try running npm run build in electron.

**Comment by nmhung1210** [comment]
Could you please share more details of the broken? The app could not able to load or something else?

**Comment by nmhung1210** [comment]
Closed via #869
