### ISSUE TITLE
bid window not refresh balance after bid complete

### ISSUE THREAD

**Issue by wqwqwq219** [iotexproject/iotex-explorer#860]
![pic](https://user-images.githubusercontent.com/47782617/61224753-bc9b6180-a751-11e9-939b-275a70ffd9a6.png)

**Comment by guo** [comment]
reproduce：
1. bid 
2. see the balance is not deducted. the actual balance in wallet is deducted. 
3. refresh, you can see it is updated.

**Comment by wqwqwq219** [comment]
follow this step:
1.bid
2.refresh and see the balance updated in web wallet
3.click bid button again,and see the balance in the bid window not changed.

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/61226092-67ad1a80-a754-11e9-9e38-0ccda3fe3a73.png)


this dialog cached balance. showing the wrong balance.
