### ISSUE TITLE
balance does not match (see screenshot)

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#863]
![image](https://user-images.githubusercontent.com/448293/61225946-2b79ba00-a754-11e9-8234-0723c6bb8569.png)

**Comment by nmhung1210** [comment]
Closed as dicussed as below:
![image](https://user-images.githubusercontent.com/6645185/61231237-f66e6700-a755-11e9-8092-dc1b0394f4f6.png)

**Comment by guo** [comment]
add ```(total balance - action fee)```

**Comment by nmhung1210** [comment]
ok, I'll update the text to avoid potential confusion.

**Comment by nmhung1210** [comment]
@gyanpgupta please help to update the text here
