### ISSUE TITLE
better support contract address

### ISSUE THREAD

**Issue by guo** [iotexproject/iotex-explorer#864]
like this one:
https://iotexscan.io/address/io1hp6y4eqr90j7tmul4w2wa8pm7wx462hq0mg4tw
Vita Token

can refer to etherscan's page: 
https://etherscan.io/token/0x6fb3e0a217407efff7ca062d46c26e5d60a14d69

1. list all token transfers.
2. list a profile: 
  a. Total Supply: XXX
  b. Holders: (if possible)
  c. Total transfers: (if possible)
  d. Decimals:

**Comment by nmhung1210** [comment]
Closed in favor of #1028
