### ISSUE TITLE
Reduplicative ations with same hash shows in action list

### ISSUE THREAD

**Issue by anshuomomo** [iotexproject/iotex-explorer#885]
https://iotexscan.io/address/io15ed8a4lyqgglm7z9wdq40kjksc0j5z0erw5v3x 

![image](https://user-images.githubusercontent.com/16026265/61425995-66920e00-a94b-11e9-9748-3d32ebfe4b83.png)

**Comment by puncsky** [comment]
ref https://github.com/iotexproject/iotex-core/issues/1386

**Comment by nmhung1210** [comment]
Closed in favor of https://github.com/iotexproject/iotex-core/issues/1386
