### ISSUE TITLE
timeout lock is not working in wallet

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#889]
The lock modal is hanging there always, and it is not locked automatically.

**Comment by sxlwar** [comment]
could you please provide some more specific steps to reproduce this issue?

my steps:

set after and remain10 for test purpose: 
![image](https://user-images.githubusercontent.com/20088392/61590120-67929c00-abe6-11e9-9906-4922d1dabd4e.png)
![image](https://user-images.githubusercontent.com/20088392/61590129-7bd69900-abe6-11e9-8517-4ad3682d479a.png)

1. click on  1, 2, 3 in the screenshot below when modal appears, or without any operation, the page will be locked after 10 seconds.
![image](https://user-images.githubusercontent.com/20088392/61590153-df60c680-abe6-11e9-9c3e-b2646015ce96.png)

2. If i click the 'yes, dismiss the lock' button when modal appears, it will re-enter a new timing cycle.

3.  Unlock the wallet first , then go to another page (e.g, dashboard).After the timer expires, go back to wallet page, and the page is locked.
