### ISSUE TITLE
stats bugs

### ISSUE THREAD

**Issue by CoderZhi** [iotexproject/iotex-explorer#891]
![image](https://user-images.githubusercontent.com/35643171/61654452-4fb42a00-ac71-11e9-9483-2a6df93fe0e0.png)

1. The TPS is a float number
2. Productivity calculation is wrong. Hide the graph before we figure out the right way to calculate it
3. Number of consensus delegate is wrong. It is supposed to be 24, we need to review the implementation

**Comment by CoderZhi** [comment]
The first issue is a problem in iotex-analytics. I will ask the corresponding engineer to fix it.

**Comment by CoderZhi** [comment]
For 3, https://github.com/iotexproject/iotex-explorer/blob/43a4136afb52324205cca77a93840c83a36900f9/src/shared/home/stats/candidates-card.tsx#L48 should be the ones with "productivityBase !== 0"

**Comment by CoderZhi** [comment]
For 2, query https://github.com/iotexproject/iotex-analytics/blob/0786372110db3928815bab9ee2727acd064dca8c/queryprotocol/productivity/protocol.go#L73 instead

**Comment by nmhung1210** [comment]
> For 2, query https://github.com/iotexproject/iotex-analytics/blob/0786372110db3928815bab9ee2727acd064dca8c/queryprotocol/productivity/protocol.go#L73 instead

It seems GraphQL schema at https://github.com/iotexproject/iotex-analytics/blob/0786372110db3928815bab9ee2727acd064dca8c/graphql/schema.graphql was not updated yet. When can we have it available?
