### ISSUE TITLE
[UI][Address page] Update address overview block

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-explorer#897]
**Current**
![image](https://user-images.githubusercontent.com/6645185/61816034-b7d35d80-ae75-11e9-9e67-8547f6245f40.png)

**New Design**

![image](https://user-images.githubusercontent.com/6645185/61816101-dc2f3a00-ae75-11e9-8ff4-c4439707d5fd.png)

Ref: https://app.zeplin.io/project/5c81bede826def625074c12c/screen/5cd79d03cbd69a34a8c73303

**Comment by gyanpgupta** [comment]
@nmhung1210  where can I get age and this Name tag for address and what are those two new icons for the **(+)** one and the **forward or share**?
and there's only transactions and in the table Data is the Gas Fee correct?
could you please explain?
