### ISSUE TITLE
[UI][Address Page] Update transaction list 

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-explorer#898]
**Current**
![image](https://user-images.githubusercontent.com/6645185/61816449-94f57900-ae76-11e9-9507-bcec46c6ed34.png)

**New Design**

![image](https://user-images.githubusercontent.com/6645185/61816384-73948d00-ae76-11e9-958e-3ed2ecb23a30.png)

Ref. https://app.zeplin.io/project/5c81bede826def625074c12c/screen/5cd79d03cbd69a34a8c73303

**Comment by gyanpgupta** [comment]
@nmhung1210  what is gasFee and Type here? and where can I get these two?

**Comment by nmhung1210** [comment]
> @nmhung1210 what is gasFee and Type here? and where can I get these two? Do I need to add datetime filter on timestamp and also csv export?

GasFee is how much gas consumed for the transaction. Yes, we need to reflect the design for this page.

**Comment by nmhung1210** [comment]
Closed in favor of #1028
