### ISSUE TITLE
Productivity chart is misleading

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#937]
I guess the number = avg(produced blocks / total blocks to produce in an epoch).

This is not useful. It will grow from 0 to 100% during one epoch. More importantly, at the beginning of an epoch, people will wrongly think the productivity is so low

<img width="462" alt="Screen Shot 2019-08-05 at 10 24 34 PM" src="https://user-images.githubusercontent.com/35021395/62513191-f3541d00-b7cf-11e9-8a12-88fde3b4a756.png">

**Comment by guo** [comment]
per discussion. let's change the title of the chart to "Progress of Epoch"
