### ISSUE TITLE
[GraphQL API] Support date range & xrc20 filters for getActions query

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-explorer#947]
According to new UI kit v2 for the explorer at https://app.zeplin.io/project/5c81bede826def625074c12c/screen/5cd79d03cbd69a34a8c73303, we would need backend support for getting a list of actions by date and erc20 filters as below:

![image](https://user-images.githubusercontent.com/6645185/62831793-97194f00-bc4e-11e9-8992-0955492fa342.png)

**Comment by puncsky** [comment]
https://analytics.iotexscan.io/

action: Action

type Action {
    byDates(startDate: Int!, endDate: Int!): [ActionInfo]!
}

type ActionInfo {
    actHash: String!
    blkHash: String!
    timeStamp: Int!
    actType: String!
    sender: String!
    recipient: String!
    amount: String!
}

**Comment by nmhung1210** [comment]
> https://analytics.iotexscan.io/
> 
> ```
> action: Action
> 
> type Action {
>     byDates(startDate: Int!, endDate: Int!): [ActionInfo]!
> }
> 
> type ActionInfo {
>     actHash: String!
>     blkHash: String!
>     timeStamp: Int!
>     actType: String!
>     sender: String!
>     recipient: String!
>     amount: String!
> }
> ```

We would need limit & offset too. Could you please add it?

**Comment by lizhefeng** [comment]
Sure. Will add it.

**Comment by puncsky** [comment]
@lizhefeng any update on this?

**Comment by lizhefeng** [comment]
It is done.

**Comment by lizhefeng** [comment]
```
action: Action

type Action {
    byDates(startDate: Int!, endDate: Int!): ActionList
}

type ActionList {
    exist: Boolean!
    actions(pagination: Pagination): [ActionInfo]!
    count: Int!
}
```
