### ISSUE TITLE
Show XRC20 token transfer in receiver's tx logs bug

### ISSUE THREAD

**Issue by FishMeat** [iotexproject/iotex-explorer#951]
I send some VITA to an receiver
[https://iotexscan.io/action/77eed89c8307a96a8f1bc7d54eb6749f20940ca46cf47a8bf92834835b7a867e](https://iotexscan.io/action/77eed89c8307a96a8f1bc7d54eb6749f20940ca46cf47a8bf92834835b7a867e)

but in receiver's tx logs, I didn't see this XRC20's tx log
[https://iotexscan.io/address/io1cnq64jkkrg2ga2fx2q0209mgkw93js8c0a8rgc](https://iotexscan.io/address/io1cnq64jkkrg2ga2fx2q0209mgkw93js8c0a8rgc)

**Comment by nmhung1210** [comment]
Closed in favor of #1028
