### ISSUE TITLE
add analytics for iopay wallet

### ISSUE THREAD

**Issue by puncsky** [iotexproject/iotex-explorer#959]
use UA-111756489-15

**Comment by nmhung1210** [comment]
@gyanpgupta the iopay wallet is the electron app located at `src/electron`. You might need to use `electron-ga` package for this. (Check https://www.npmjs.com/package/electron-ga for how to use it).

**Comment by nmhung1210** [comment]
@puncsky what do you want to track for the iopay wallet?
