### ISSUE TITLE
Add spin up for the Candidates number

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-explorer#967]
Current the candidate's number in the stats card does not spin up as expected. Pls. help fix it.

![image](https://user-images.githubusercontent.com/6645185/63589206-7b655f80-c5e3-11e9-9d3e-a0bec072b7ba.png)

**Comment by gyanpgupta** [comment]
![candidatesSpinup](https://user-images.githubusercontent.com/36037560/63676214-12126600-c808-11e9-8452-fe18bbdf51d5.gif)

its working like this already what's needs to be changed? @nmhung1210

**Comment by puncsky** [comment]
`/ 68` looks buggy
