### ISSUE TITLE
Add VITA Balance in Explorer

### ISSUE THREAD

**Issue by loriIoTeX** [iotexproject/iotex-explorer#983]
![image](https://user-images.githubusercontent.com/38968374/63984835-e13d6580-ca81-11e9-8b7e-296caca47c9b.png)

**Comment by DengMMM** [comment]
![balance](https://user-images.githubusercontent.com/50934079/63990409-7be78400-cb16-11e9-8abe-f9b01c7b0d2f.png)
[icon_balance.zip](https://github.com/iotexproject/iotex-explorer/files/3558121/icon_balance.zip)

**Comment by nmhung1210** [comment]
Closed due to  #903
