### ISSUE TITLE
API queries list of XRC20 transfers by wallet address

### ISSUE THREAD

**Issue by nmhung1210** [iotexproject/iotex-explorer#994]
This is separated from https://github.com/iotexproject/iotex-explorer/issues/731 for list of XRC20 transfers by wallet address

**Comment by lizhefeng** [comment]
https://github.com/iotexproject/iotex-analytics/issues/84

**Comment by lizhefeng** [comment]
@nmhung1210 Do we need to separate two APIs for recipient address and sender address or just byAddress in one API?

**Comment by nmhung1210** [comment]
@lizhefeng I would refer one API that returns both in/out transfers for a wallet address. It's better, I think.
