### ISSUE TITLE
Bad alignment on mobile to show an action

### ISSUE THREAD

**Issue by zjshen14** [iotexproject/iotex-explorer#997]
On safari on iPhone

![BA24AB6D-3592-4EE5-B6E8-C80329773E1C](https://user-images.githubusercontent.com/35021395/64668980-9ffb6d00-d414-11e9-88ae-9fd54b602827.png)

**Comment by gyanpgupta** [comment]
![safariIphone8](https://user-images.githubusercontent.com/36037560/65483632-92d18a00-deba-11e9-95a0-5d5151b90c6c.png)

@nmhung1210  could not reproduce this. added screenshot from safari with iphone.
