### ISSUE TITLE
[wallet] console warning

### ISSUE THREAD

**Issue by sxlwar** [iotexproject/iotex-explorer#998]
![image](https://user-images.githubusercontent.com/20088392/64693182-40ab6480-d4c9-11e9-972c-19c0cab65d22.png)

confused why there is a  warning here

**Comment by nmhung1210** [comment]
> ![image](https://user-images.githubusercontent.com/20088392/64693182-40ab6480-d4c9-11e9-972c-19c0cab65d22.png)
> 
> confused why there is a warning here

Because It shares UI code for the wallet in the browser and the electron app. The browser wallet has same issue.
